Setup a Redis vector store that works with LlamaIndex for the FAQ, amenities, and services info.

I provide metadata information because it's useful to the user and LlamaIndex can have the LLM filter by it.

Load environment variables from .env file

In [1]:
import os

from dotenv import load_dotenv

load_dotenv()

True

For info on what's happening in the background

In [2]:
import logging
import sys

logging.basicConfig(stream=sys.stdout, level=logging.INFO)
logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))

Setup the embedding model

Use HuggingFaceEmbedding running locally because OpenAIEmbedding takes a long time to initialize.

In [3]:
from llama_index.core import Settings
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.llms.openai import OpenAI
# from llama_index.embeddings.openai import OpenAIEmbedding
# from llama_index.embeddings.google_genai import GoogleGenAIEmbedding

In [4]:
# Settings.embed_model = OpenAIEmbedding(model="text-embedding-3-small", batch_size=10, dimensions=512)
# Settings.embed_model = OpenAIEmbedding()
Settings.embed_model = HuggingFaceEmbedding("BAAI/bge-small-en-v1.5")
# Settings.embed_model = GoogleGenAIEmbedding("gemini-embedding-001", dimensions=768)

INFO:sentence_transformers.SentenceTransformer:Load pretrained SentenceTransformer: BAAI/bge-small-en-v1.5
Load pretrained SentenceTransformer: BAAI/bge-small-en-v1.5
INFO:httpx:HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json "HTTP/1.1 200 OK"
HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config_sentence_transformers.json "HTTP/1.1 200 OK"
HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config_sentence_transformers.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config_sentence_transformers.json "HTTP/1.1 200 OK"
HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config_sentence_transformers.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/README.md "HTTP/1.1 200 OK"
HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/README.md "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json "HTTP/1.1 200 OK"
HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/sentence_bert_config.json "HTTP/1.1 307 Temporary Redirect"
HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/sentence_bert_config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/sentence_bert_config.json "HTTP/1.1 200 OK"
HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/sentence_bert_config.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json "HTTP/1.1 200 OK"
HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json "HTTP/1.1 200 OK"

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: BAAI/bge-small-en-v1.5
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

INFO:httpx:HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/tokenizer_config.json "HTTP/1.1 200 OK"
HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/tokenizer_config.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
INFO:httpx:HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/1_Pooling/config.json "HTTP/1.1 307 Temporary Redirect"
HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/1_Pooling/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/1_Pooling%2Fconfig.json "HTTP/1.1 200 OK"
HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/1_Pooling%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5 "HTTP/1.1 200 OK"
HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5 "HTTP/1.1 200 OK"
INFO:sentence_transformers.SentenceTransformer:1 prompt is loaded, with the key: query
1 prompt is loaded, with the key: query

In [5]:
Settings.llm = OpenAI("gpt-5.2", temperature=0, reasoning={"effort":"medium"})

### Typing for Retrievers

In [6]:
from typing import Any
from pydantic import BaseModel, Field

class RetrievalItem(BaseModel):
    source: str = Field(..., description="Which retriever produced this item: FAQ, amenities, or services")
    metadata: dict[str, Any] = Field(..., description="The metadata associated with the text.")
    text: str = Field(..., description="The item name and description")
    score: float = Field(..., description="Similarity score; higher is more relevant")

### FAQ

Connect to Redis Cloud

In [7]:
from llama_index.core import StorageContext, VectorStoreIndex
from llama_index.vector_stores.redis import RedisVectorStore
from redisvl.schema import IndexSchema
from redis import Redis

redis_conn_string = os.getenv("REDIS_URL")
schema = IndexSchema.from_dict(
    {
        "index": {"name": "FAQ", "prefix": "FAQ"},
        # customize fields that are indexed
        "fields": [
            # required fields for llamaindex
            {"type": "tag", "name": "id"},
            {"type": "tag", "name": "doc_id"},
            {"type": "text", "name": "text"},
            # custom for metadata filtering
            {"type": "tag", "name": "category"},
            # custom vector field for bge-small-en-v1.5
            {
                "type": "vector",
                "name": "vector",
                "attrs": {
                    "dims": 384,
                    "algorithm": "hnsw",
                    "distance_metric": "cosine",
                },
            },
        ],
    },
)
redis_client = Redis.from_url(redis_conn_string, decode_responses=True)
vector_store = RedisVectorStore(schema=schema, redis_client=redis_client, overwrite=True)
storage_context = StorageContext.from_defaults(vector_store=vector_store)

15:00:23 redisvl.index.index INFO   Index already exists, overwriting.
15:00:23 redisvl.index.index INFO   Index already exists, overwriting.

Load the FAQ

In [8]:
import pandas as pd

df_faq = pd.read_pickle("../data/pandas/faq_knowledge_base.pkl")
df_faq

,category,subcategory,question,answer,keywords,last_updated,helpful_votes,views
faq_id,,,,,,,,
FAQ000001,booking,reservations,How do I make a reservation?,You can make a reservation through our website...,"book, reserve, reservation, booking",2024-03-09,957,3813
FAQ000002,booking,check-in/out,What is the check-in/check-out time?,Check-in time is 3:00 PM and check-out time is...,"check in, check out, arrival, departure",2024-10-15,967,2793
FAQ000003,booking,modifications,Can I modify my booking?,"Yes, you can modify your booking through our w...","change, modify, update, edit",2024-12-05,443,1929
FAQ000004,booking,cancellations,What is the cancellation policy?,Free cancellation is available up to 48 hours ...,"cancel, refund, cancellation",2024-05-20,611,1300
FAQ000005,booking,special requests,Do you offer early check-in/late check-out?,"Subject to availability, early check-in and la...","early check-in, late check-out, extended stay",2024-12-18,239,3954
FAQ000006,amenities,facilities,What amenities are included?,"Our hotel offers complimentary Wi-Fi, fitness ...","amenities, facilities, services",2024-10-24,855,1860
FAQ000007,amenities,dining,Is breakfast included?,"Yes, breakfast is included with most room rate...","breakfast, dining, restaurant",2024-01-10,365,1943
FAQ000008,amenities,wellness,Do you have a fitness center?,"Yes, our fitness center is open 24/7 and featu...","fitness, gym, exercise",2024-10-05,988,1471
FAQ000009,amenities,business,Is there a swimming pool?,"Yes, we have both indoor and outdoor pools ope...","pool, swimming, recreation",2024-10-15,400,2881
FAQ000010,amenities,recreation,Do you offer spa services?,"Our full-service spa offers massages, facials,...","spa, wellness, treatments",2024-01-07,145,766
FAQ000011,services,room service,Is room service available?,Room service is available 24/7 with a full men...,"room service, dining, food",2024-04-05,708,2133
FAQ000012,services,housekeeping,Do you offer laundry service?,"Yes, same-day laundry and dry-cleaning service...","laundry, cleaning, housekeeping",2024-09-16,126,249
FAQ000013,services,concierge,Is there a business center?,Our business center is open 24/7 and offers co...,"business, work, office",2024-05-25,925,1604
FAQ000014,services,transportation,Do you provide airport transfers?,"Yes, we offer airport shuttle service for a fe...","airport, shuttle, transfer",2024-11-27,743,1621
FAQ000015,services,business,Is parking available?,We offer both self-parking and valet parking s...,"parking, valet, car",2024-02-03,721,1975
FAQ000016,policies,pet policy,What is your pet policy?,We welcome pets under 25 pounds for an additio...,"pets, animals, dogs, cats",2024-07-17,639,4327
FAQ000017,policies,smoking policy,Do you have smoking rooms?,All our rooms are non-smoking. Smoking is only...,"smoking, non-smoking, tobacco",2024-01-31,703,2992
FAQ000018,policies,payment policy,What forms of payment do you accept?,"We accept all major credit cards, debit cards,...","payment, credit card, cash",2024-10-30,799,2778
FAQ000019,policies,age requirements,Is there a minimum age to check in?,Guests must be 18 or older to check in. Valid ...,"age, check-in, requirements",2024-01-09,662,4150
FAQ000020,policies,luggage policy,What is your luggage storage policy?,Complimentary luggage storage is available bef...,"luggage, storage, bags",2024-06-20,127,213

Prepare data for storage

In [9]:
from llama_index.core.schema import TextNode


def get_faq_nodes() -> list:
    nodes = []
    for id_, row in df_faq.iterrows():
        main_text = "Question:\n" + row["question"] + "\n\nAnswer:\n" + row["answer"]
        metadata = {"category": row["category"],
                    "subcategory": row["subcategory"],
                    "keywords": row["keywords"],
                    "last_updated": row["last_updated"]}
        node = TextNode(text=main_text, id_=id_, metadata=metadata)
        nodes.append(node)
    return nodes

nodes = get_faq_nodes()

Store in vector store

In [10]:
faq_index = VectorStoreIndex(nodes=nodes, storage_context=storage_context)

15:00:24 llama_index.vector_stores.redis.base INFO   Added 20 documents to index FAQ
15:00:24 llama_index.vector_stores.redis.base INFO   Added 20 documents to index FAQ

Setup and test retrieval

In [11]:
faq_retriever = faq_index.as_retriever(similarity_top_k=4)

In [12]:
faq_retriever.retrieve("Is there a place to swim?")

15:00:24 llama_index.vector_stores.redis.base INFO   Querying index FAQ with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
15:00:24 llama_index.vector_stores.redis.base INFO   Querying index FAQ with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
15:00:24 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['FAQ:FAQ000009', 'FAQ:FAQ000006', 'FAQ:FAQ000010', 'FAQ:FAQ000008']
15:00:24 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['FAQ:FAQ000009', 'FAQ:FAQ000006', 'FAQ:FAQ000010', 'FAQ:FAQ000008']

[NodeWithScore(node=TextNode(id_='FAQ000009', embedding=None, metadata={'category': 'amenities', 'subcategory': 'business', 'keywords': 'pool, swimming, recreation', 'last_updated': '2024-10-15'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Question:\nIs there a swimming pool?\n\nAnswer:\nYes, we have both indoor and outdoor pools open from 6:00 AM to 10:00 PM.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.741773724556),
 NodeWithScore(node=TextNode(id_='FAQ000006', embedding=None, metadata={'category': 'amenities', 'subcategory': 'facilities', 'keywords': 'amenities, facilities, services', 'last_updated': '2024-10-24'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Question:\nWhat amenities are included?\n\nAnswer:\nOur hotel offers complimentary Wi-Fi, fitness center, pool, spa, restaurant, and 24-hour room service.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.651285409927),
 NodeWithScore(node=TextNode(id_='FAQ000010', embedding=None, metadata={'category': 'amenities', 'subcategory': 'recreation', 'keywords': 'spa, wellness, treatments', 'last_updated': '2024-01-07'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Question:\nDo you offer spa services?\n\nAnswer:\nOur full-service spa offers massages, facials, and body treatments. Advance booking is recommended.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.650461614132),
 NodeWithScore(node=TextNode(id_='FAQ000008', embedding=None, metadata={'category': 'amenities', 'subcategory': 'wellness', 'keywords': 'fitness, gym, exercise', 'last_updated': '2024-10-05'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Question:\nDo you have a fitness center?\n\nAnswer:\nYes, our fitness center is open 24/7 and features modern equipment and free weights.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.6396026015280001)]

Setup and auto-retriever that filters over metadata.

Whether it works depends heavily on the model chosen. gpt-5-mini causes an error sometimes. I won't include this in the production code for the FAQ as there's little point.

In [13]:
index_name = vector_store.index_name
categories = redis_client.ft(index_name).tagvals("category")
print(categories)

['amenities', 'booking', 'policies', 'services']

In [14]:
from llama_index.core.retrievers import VectorIndexAutoRetriever
from llama_index.core.vector_stores.types import MetadataInfo, VectorStoreInfo

faq_store_info = VectorStoreInfo(
    content_info="FAQs and their answers for the hotel",
    metadata_info=[
        MetadataInfo(
            name="category",
            type="tag",
            description=f"Category of the FAQ, one of {categories}",
        ),
    ],
)
retriever=VectorIndexAutoRetriever(faq_index, vector_store_info=faq_store_info, similarity_top_k=4)

The auto-retriever works well with gpt-5, but it's slow. gpt-5.1 and gpt-5.2 often don't filter at all.

In [15]:
retriever.retrieve("Is there a place to swim?")

15:00:27 httpx INFO   HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
15:00:27 httpx INFO   HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
15:00:27 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using query str: place to swim
15:00:27 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using query str: place to swim
15:00:27 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using filters: []
15:00:27 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using filters: []
15:00:27 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using top_k: 4
15:00:27 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using top_k: 4
15:00:27 llama_index.vector_stores.redis.base INFO   Querying index FAQ with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
15:00:27 llama_index.vector_stores.redis.base INFO   Querying index FAQ with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
15:00:27 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['FAQ:FAQ000009', 'FAQ:FAQ000010', 'FAQ:FAQ000006', 'FAQ:FAQ000008']
15:00:27 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['FAQ:FAQ000009', 'FAQ:FAQ000010', 'FAQ:FAQ000006', 'FAQ:FAQ000008']

[NodeWithScore(node=TextNode(id_='FAQ000009', embedding=None, metadata={'category': 'amenities', 'subcategory': 'business', 'keywords': 'pool, swimming, recreation', 'last_updated': '2024-10-15'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Question:\nIs there a swimming pool?\n\nAnswer:\nYes, we have both indoor and outdoor pools open from 6:00 AM to 10:00 PM.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.7269672751430001),
 NodeWithScore(node=TextNode(id_='FAQ000010', embedding=None, metadata={'category': 'amenities', 'subcategory': 'recreation', 'keywords': 'spa, wellness, treatments', 'last_updated': '2024-01-07'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Question:\nDo you offer spa services?\n\nAnswer:\nOur full-service spa offers massages, facials, and body treatments. Advance booking is recommended.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.6523479223249999),
 NodeWithScore(node=TextNode(id_='FAQ000006', embedding=None, metadata={'category': 'amenities', 'subcategory': 'facilities', 'keywords': 'amenities, facilities, services', 'last_updated': '2024-10-24'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Question:\nWhat amenities are included?\n\nAnswer:\nOur hotel offers complimentary Wi-Fi, fitness center, pool, spa, restaurant, and 24-hour room service.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.645174145699),
 NodeWithScore(node=TextNode(id_='FAQ000008', embedding=None, metadata={'category': 'amenities', 'subcategory': 'wellness', 'keywords': 'fitness, gym, exercise', 'last_updated': '2024-10-05'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Question:\nDo you have a fitness center?\n\nAnswer:\nYes, our fitness center is open 24/7 and features modern equipment and free weights.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.6159504055980001)]

In [16]:
retriever.retrieve("What's the policy on smoking?")

15:00:29 httpx INFO   HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
15:00:29 httpx INFO   HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
15:00:29 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using query str: policy on smoking
15:00:29 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using query str: policy on smoking
15:00:29 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using filters: []
15:00:29 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using filters: []
15:00:29 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using top_k: 4
15:00:29 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using top_k: 4
15:00:29 llama_index.vector_stores.redis.base INFO   Querying index FAQ with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
15:00:29 llama_index.vector_stores.redis.base INFO   Querying index FAQ with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
15:00:29 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['FAQ:FAQ000017', 'FAQ:FAQ000016', 'FAQ:FAQ000020', 'FAQ:FAQ000018']
15:00:29 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['FAQ:FAQ000017', 'FAQ:FAQ000016', 'FAQ:FAQ000020', 'FAQ:FAQ000018']

[NodeWithScore(node=TextNode(id_='FAQ000017', embedding=None, metadata={'category': 'policies', 'subcategory': 'smoking policy', 'keywords': 'smoking, non-smoking, tobacco', 'last_updated': '2024-01-31'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Question:\nDo you have smoking rooms?\n\nAnswer:\nAll our rooms are non-smoking. Smoking is only permitted in designated outdoor areas.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.786777734756),
 NodeWithScore(node=TextNode(id_='FAQ000016', embedding=None, metadata={'category': 'policies', 'subcategory': 'pet policy', 'keywords': 'pets, animals, dogs, cats', 'last_updated': '2024-07-17'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Question:\nWhat is your pet policy?\n\nAnswer:\nWe welcome pets under 25 pounds for an additional fee. Please notify us in advance.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.6674103736879999),
 NodeWithScore(node=TextNode(id_='FAQ000020', embedding=None, metadata={'category': 'policies', 'subcategory': 'luggage policy', 'keywords': 'luggage, storage, bags', 'last_updated': '2024-06-20'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Question:\nWhat is your luggage storage policy?\n\nAnswer:\nComplimentary luggage storage is available before check-in and after check-out.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.6227447390559999),
 NodeWithScore(node=TextNode(id_='FAQ000018', embedding=None, metadata={'category': 'policies', 'subcategory': 'payment policy', 'keywords': 'payment, credit card, cash', 'last_updated': '2024-10-30'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Question:\nWhat forms of payment do you accept?\n\nAnswer:\nWe accept all major credit cards, debit cards, and cash with a security deposit.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.613159239292)]

### Amenities

Connect to Redis Cloud

In [17]:
from llama_index.core import StorageContext, VectorStoreIndex
from llama_index.vector_stores.redis import RedisVectorStore
from redisvl.schema import IndexSchema
from redis import Redis

redis_conn_string = os.getenv("REDIS_URL")
schema = IndexSchema.from_dict(
    {
        "index": {"name": "Amenities", "prefix": "Amenities"},
        # customize fields that are indexed
        "fields": [
            # required fields for llamaindex
            {"type": "tag", "name": "id"},
            {"type": "tag", "name": "doc_id"},
            {"type": "text", "name": "text"},
            # custom fields for filtering
            {"type": "tag", "name": "category"},
            {"type": "numeric", "name": "price"},
            {"type": "numeric", "name": "duration"},
            {"type": "numeric", "name": "min_notice_hours"},
            {"type": "tag", "name": "booking_required"},
            # custom vector field for bge-small-en-v1.5 embeddings
            {
                "type": "vector",
                "name": "vector",
                "attrs": {
                    "dims": 384,
                    "algorithm": "hnsw",
                    "distance_metric": "cosine",
                },
            },
        ],
    },
)
redis_client = Redis.from_url(redis_conn_string, decode_responses=True)
vector_store = RedisVectorStore(schema=schema, redis_client=redis_client, overwrite=True)
storage_context = StorageContext.from_defaults(vector_store=vector_store)

15:00:29 redisvl.index.index INFO   Index already exists, overwriting.
15:00:29 redisvl.index.index INFO   Index already exists, overwriting.

Add amenity information

In [18]:
import pandas as pd

df_amenities = pd.read_pickle("../data/pandas/amenities.pkl")
df_amenities.head()

,category,name,price,duration,description,availability,booking_required,min_notice_hours
amenity_id,,,,,,,,
AM000001,Spa Services,Swedish Massage,120,60,Experience pure relaxation with our Swedish Ma...,24/7,True,2
AM000002,Spa Services,Deep Tissue Massage,140,60,"Indulge in our signature Deep Tissue Massage, ...",6:00-22:00,False,4
AM000003,Spa Services,Couples Massage Experience,280,90,Indulge in our signature Couples Massage Exper...,By appointment only,False,0
AM000004,Spa Services,Hot Stone Therapy,160,90,Experience pure relaxation with our Hot Stone ...,6:00-22:00,False,1
AM000005,Spa Services,Luxury Facial Treatment,180,90,Indulge in our signature Luxury Facial Treatme...,24/7,False,24

Prepare data for storage

In [19]:
from llama_index.core.schema import TextNode

def get_amenities_nodes() -> list[TextNode]:
    nodes = []
    for id_, row in df_amenities.iterrows():
        main_text = "Name:" + row["name"] + "\n\nDescription:\n" + row["description"]
        metadata = {"category": row["category"],
                    "price": row["price"],
                    "duration": row["duration"],
                    "availability": row["availability"],
                    "booking_required": str(row["booking_required"]),
                    "min_notice_hours": row["min_notice_hours"]}
        node = TextNode(text=main_text, id_=id_, metadata=metadata)
        nodes.append(node)
    return nodes

nodes = get_amenities_nodes()

Store in vector store, setup retriever

In [20]:
amenities_index = VectorStoreIndex(nodes=nodes, storage_context=storage_context)
retriever = amenities_index.as_retriever(similarity_top_k=4)

15:00:30 llama_index.vector_stores.redis.base INFO   Added 34 documents to index Amenities
15:00:30 llama_index.vector_stores.redis.base INFO   Added 34 documents to index Amenities

In [21]:
retriever.retrieve("Can I get a massage?")

15:00:30 llama_index.vector_stores.redis.base INFO   Querying index Amenities with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
15:00:30 llama_index.vector_stores.redis.base INFO   Querying index Amenities with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
15:00:30 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['Amenities:AM000003', 'Amenities:AM000001', 'Amenities:AM000002', 'Amenities:AM000007']
15:00:30 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['Amenities:AM000003', 'Amenities:AM000001', 'Amenities:AM000002', 'Amenities:AM000007']

[NodeWithScore(node=TextNode(id_='AM000003', embedding=None, metadata={'category': 'Spa Services', 'price': 280, 'duration': 90, 'availability': 'By appointment only', 'booking_required': 'False', 'min_notice_hours': 0}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Name:Couples Massage Experience\n\nDescription:\nIndulge in our signature Couples Massage Experience, where 90 minutes of expert care will melt away stress and tension. This treatment features therapeutic-grade materials and customized therapeutic approaches to provide rejuvenated and restored.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.666032791138),
 NodeWithScore(node=TextNode(id_='AM000001', embedding=None, metadata={'category': 'Spa Services', 'price': 120, 'duration': 60, 'availability': '24/7', 'booking_required': 'True', 'min_notice_hours': 2}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Name:Swedish Massage\n\nDescription:\nExperience pure relaxation with our Swedish Massage, a 60-minute treatment designed to melt away stress and tension. Our certified therapists use premium natural skincare products to precise pressure point therapy, leaving you feeling renewed and revitalized.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.6470060348510001),
 NodeWithScore(node=TextNode(id_='AM000002', embedding=None, metadata={'category': 'Spa Services', 'price': 140, 'duration': 60, 'availability': '6:00-22:00', 'booking_required': 'False', 'min_notice_hours': 4}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Name:Deep Tissue Massage\n\nDescription:\nIndulge in our signature Deep Tissue Massage, where 60 minutes of expert care will melt away stress and tension. This treatment features natural skincare products and customized therapeutic approaches to provide rejuvenated and restored.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.645396232605),
 NodeWithScore(node=TextNode(id_='AM000007', embedding=None, metadata={'category': 'Spa Services', 'price': 150, 'duration': 75, 'availability': '6:00-22:00', 'booking_required': 'False', 'min_notice_hours': 0}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Name:Aromatherapy Journey\n\nDescription:\nExperience pure relaxation with our Aromatherapy Journey, a 75-minute treatment designed to promote deep relaxation and healing. Our certified therapists use premium natural skincare products to precise pressure point therapy, leaving you feeling deeply relaxed and refreshed.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.622757196426)]

Setup and auto-retriever that filters over metadata

In [22]:
index_name = vector_store.index_name
categories = redis_client.ft(index_name).tagvals("category")
print(f"categories = {categories}")

categories = ['business services', 'childcare services', 'entertainment services', 'fitness services', 'luxury water sports', 'room service', 'spa services', 'transportation services']

In [23]:
from llama_index.core.retrievers import VectorIndexAutoRetriever
from llama_index.core.vector_stores.types import (
    FilterOperator,
    MetadataFilter,
    MetadataFilters,
    MetadataInfo,
    VectorStoreInfo,
)

amenities_store_info = VectorStoreInfo(
    content_info="Information about hotel amenities",
    metadata_info=[
        MetadataInfo(
            name="category",
            type="tag",
            description=f"Category of the amenity, one of {categories}",
        ),
        MetadataInfo(
            name="booking_required",
            type="tag",
            description="Whether a booking is requried for the amenity, either 'True' or 'False'. 'False' does NOT imply min_notice_hours=0.",
        ),
    ],
)

def _range_filters(
    *,
    min_price: float | None = None,
    max_price: float | None = None,
    min_notice_hours: int | None = None,
    max_notice_hours: int | None = None,
    min_duration_minutes: int | None = None,
    max_duration_minutes: int | None = None,
) -> MetadataFilters | None:
    filters: list[MetadataFilter] = []

    if min_price is not None:
        filters.append(MetadataFilter(key="price", operator=FilterOperator.GTE, value=float(min_price)))
    if max_price is not None:
        filters.append(MetadataFilter(key="price", operator=FilterOperator.LTE, value=float(max_price)))

    if min_notice_hours is not None:
        filters.append(MetadataFilter(key="min_notice_hours", operator=FilterOperator.GTE, value=int(min_notice_hours)))
    if max_notice_hours is not None:
        filters.append(MetadataFilter(key="min_notice_hours", operator=FilterOperator.LTE, value=int(max_notice_hours)))

    if min_duration_minutes is not None:
        filters.append(MetadataFilter(key="duration", operator=FilterOperator.GTE, value=int(min_duration_minutes)))
    if max_duration_minutes is not None:
        filters.append(MetadataFilter(key="duration", operator=FilterOperator.LTE, value=int(max_duration_minutes)))

    return MetadataFilters(filters=filters) if filters else None

In [24]:
from langchain.tools import tool
from langchain_openai import ChatOpenAI

gpt_version = "gpt-5.2"
Settings.llm = OpenAI(gpt_version, temperature=0, reasoning={"effort": "medium"})

@tool(parse_docstring=True)
def query_amenities(
    query: str,
    min_price: float | None = None,
    max_price: float | None = None,
    min_notice_hours: int | None = None,
    max_notice_hours: int | None = None,
    min_duration_minutes: int | None = None,
    max_duration_minutes: int | None = None,
) -> list[RetrievalItem]:
    """Provide information about the hotel amenities in response to a passed-in query.

    Supports optional range filtering on numeric fields.

    Args:
        query (string): The query string.
        min_price (float, optional): Minimum price (inclusive).
        max_price (float, optional): Maximum price (inclusive).
        min_notice_hours (int, optional): Minimum notice hours (inclusive).
        max_notice_hours (int, optional): Maximum notice hours (inclusive).
        min_duration_minutes (int, optional): Minimum duration in minutes (inclusive).
        max_duration_minutes (int, optional): Maximum duration in minutes (inclusive).

    Returns:
        list[RetrievalItem]: The retrieved results and their associated source,
        metadata, and RAG similarity score.

    """
    filters = _range_filters(
        min_price=min_price,
        max_price=max_price,
        min_notice_hours=min_notice_hours,
        max_notice_hours=max_notice_hours,
        min_duration_minutes=min_duration_minutes,
        max_duration_minutes=max_duration_minutes,
    )

    amenities_retriever = VectorIndexAutoRetriever(
        amenities_index, extra_filters=filters, vector_store_info=amenities_store_info,
        similarity_top_k=4)

    nodes = amenities_retriever.retrieve(query)

    return [RetrievalItem(source = "amenities",
                          metadata = dict(getattr(n, "metadata", {})),
                          text = getattr(n, "text", ""),
                          score =  getattr(n, "score", 0))
            for n in nodes]

In [25]:
from langchain.agents import create_agent

SYSTEM_PROMPT = """You are a hotel information assistant. You must answer user questions only using information returned by the hotel amenities search tool.

**Core rules**
* Always use the tool to look up amenities relevant to the user's request before answering.
* Do not invent, guess, or infer details that are not explicitly present in tool results.
* If the user asks for something not found, say you couldn't find it and offer the closest relevant matches (if any).
* Your results are not exhaustive; do not claim completeness.
* Assume all prices are in USD unless the tool indicates otherwise.
* Do not mention "database," "RAG," "embeddings," or internal implementation. You may say you "looked it up" or "searched."

**Retrieval behavior**
* Convert the user's request into a search intent (categories, keywords, constraints like price/duration/availability).
* Prefer precision: return only amenities that clearly match the request.
* If the request is broad ("spa options"), return a small curated set (e.g., 3-8) that best represent the category.
* If the request is narrow and no exact hit exists, return near matches and explain why they're the closest.

**Response requirements**
You may provide a once sentence introduction to the results. List the relevant amenities afterwards.
For each amenity you include, present **only** the fields you have from the tool, using this schema and order:

**Name:**
**Category:**
**Price (USD):**
**Duration (minutes):**
**Availability:**
**Booking required:**
**Minimum notice (hours):**
**Description:**

* If a field is missing from the tool output, write "Not specified."
* Do not add advice, policies, instructions, or booking steps unless the tool output explicitly contains them.
* Do not offer to perform actions (booking, calling, emailing, etc.).

**After answering**
End with exactly one question:
"Is there any other information I can provide about the hotel?"
"""

llm = ChatOpenAI(model=gpt_version, temperature=0, reasoning={"effort": "medium"})
amenities_agent = create_agent(model=llm, tools=[query_amenities], system_prompt=SYSTEM_PROMPT)

In [26]:
def get_output_text(query_result) -> str:
    last_result = query_result["messages"][-1]
    for c in last_result.content:
        if "text" in c:
            return c["text"]
    return ""

gpt-5.1 keeps listing the Private Pilates Session in this test. gpt-5.2 almost never does.

In [27]:
result = amenities_agent.invoke({"messages": [{"role": "user", "content": "I would like an hour long massage"}]})
print(get_output_text(result))

15:00:35 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
15:00:35 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
15:00:37 httpx INFO   HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
15:00:37 httpx INFO   HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
15:00:37 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using query str: massage 60 minutes hour long
15:00:37 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using query str: massage 60 minutes hour long
15:00:37 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using filters: []
15:00:37 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using filters: []
15:00:37 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using top_k: 4
15:00:37 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using top_k: 4
15:00:37 llama_index.vector_stores.redis.base INFO   Querying index Amenities with query (@duration:[60 +inf] @duration:[-inf 60])=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
15:00:37 llama_index.vector_stores.redis.base INFO   Querying index Amenities with query (@duration:[60 +inf] @duration:[-inf 60])=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
15:00:37 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['Amenities:AM000001', 'Amenities:AM000002', 'Amenities:AM000011', 'Amenities:AM000009']
15:00:37 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['Amenities:AM000001', 'Amenities:AM000002', 'Amenities:AM000011', 'Amenities:AM000009']
15:00:41 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
15:00:41 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Here are the hotel’s 60-minute massage options I found:

**Name:** Swedish Massage
**Category:** Spa Services
**Price (USD):** 120
**Duration (minutes):** 60
**Availability:** 24/7
**Booking required:** True
**Minimum notice (hours):** 2
**Description:** Experience pure relaxation with our Swedish Massage, a 60-minute treatment designed to melt away stress and tension. Our certified therapists use premium natural skincare products to precise pressure point therapy, leaving you feeling renewed and revitalized.

**Name:** Deep Tissue Massage
**Category:** Spa Services
**Price (USD):** 140
**Duration (minutes):** 60
**Availability:** 6:00-22:00
**Booking required:** False
**Minimum notice (hours):** 4
**Description:** Indulge in our signature Deep Tissue Massage, where 60 minutes of expert care will melt away stress and tension. This treatment features natural skincare products and customized therapeutic approaches to provide rejuvenated and restored.

Is there any other information I can provide about the hotel?

In [28]:
result = amenities_agent.invoke({"messages": [{"role": "user", "content": "What can my kids do for a couple of hours?"}]})
print(get_output_text(result))

15:00:43 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
15:00:43 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
15:00:44 httpx INFO   HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
15:00:44 httpx INFO   HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
15:00:44 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using query str: kids children family activities game room kids club pool arcade crafts babysitting movie
15:00:44 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using query str: kids children family activities game room kids club pool arcade crafts babysitting movie
15:00:44 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using filters: []
15:00:44 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using filters: []
15:00:44 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using top_k: 4
15:00:44 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using top_k: 4
15:00:44 llama_index.vector_stores.redis.base INFO   Querying index Amenities with query (@duration:[90 +inf] @duration:[-inf 180])=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
15:00:44 llama_index.vector_stores.redis.base INFO   Querying index Amenities with query (@duration:[90 +inf] @duration:[-inf 180])=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
15:00:44 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['Amenities:AM000029', 'Amenities:AM000031', 'Amenities:AM000023', 'Amenities:AM000024']
15:00:44 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['Amenities:AM000029', 'Amenities:AM000031', 'Amenities:AM000023', 'Amenities:AM000024']
15:01:40 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
15:01:40 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Here are a few on-site options I found that can keep kids busy for about a couple of hours:

**Name:** Children’s Activity Program
**Category:** Childcare Services
**Price (USD):** 120
**Duration (minutes):** 120
**Availability:** 6:00-22:00
**Booking required:** False
**Minimum notice (hours):** 24
**Description:** Give your children an amazing time with our Children's Activity Program, where 120 minutes of age-appropriate activities provides promotes social interaction, guaranteeing happily entertained and enriched.

**Name:** Kids Club Session
**Category:** Childcare Services
**Price (USD):** 80
**Duration (minutes):** 180
**Availability:** 6:00-22:00
**Booking required:** True
**Minimum notice (hours):** 4
**Description:** Entrust your little ones to our Kids Club Session, a 180-minute program that promotes social interaction. Our certified caregivers use interactive play sessions, ensuring creatively stimulated.

**Name:** Private Movie Screening
**Category:** Entertainment Services
**Price (USD):** 300
**Duration (minutes):** 180
**Availability:** 24/7
**Booking required:** True
**Minimum notice (hours):** 24
**Description:** Immerse yourself in our Private Movie Screening, a 180-minute entertainment experience that transports you to another world. Our professional team delivers professional performance delivery, ensuring filled with joy and wonder.

Is there any other information I can provide about the hotel?

In [29]:
result = amenities_agent.invoke({"messages": [{"role": "user", "content": "What can I do at the pool?"}]})
print(get_output_text(result))

15:01:42 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
15:01:42 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
15:01:44 httpx INFO   HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
15:01:44 httpx INFO   HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
15:01:44 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using query str: pool
15:01:44 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using query str: pool
15:01:44 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using filters: []
15:01:44 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using filters: []
15:01:44 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using top_k: 4
15:01:44 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using top_k: 4
15:01:44 llama_index.vector_stores.redis.base INFO   Querying index Amenities with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
15:01:44 llama_index.vector_stores.redis.base INFO   Querying index Amenities with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
15:01:44 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['Amenities:AM000014', 'Amenities:AM000010', 'Amenities:AM000022', 'Amenities:AM000011']
15:01:44 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['Amenities:AM000014', 'Amenities:AM000010', 'Amenities:AM000022', 'Amenities:AM000011']
15:01:50 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
15:01:50 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
I looked up pool-related activities and found the following option:

**Name:** Aqua Fitness Class
**Category:** Fitness Services
**Price (USD):** 45
**Duration (minutes):** 45
**Availability:** 6:00-22:00
**Booking required:** False
**Minimum notice (hours):** 24
**Description:** Transform your fitness journey with our Aqua Fitness Class, a 45-minute session that boosts energy and vitality. Our certified trainers will progressive training methods, ensuring energized and accomplished.

I couldn’t find any other amenities explicitly tied to “the pool” beyond this class in the available listings.

Is there any other information I can provide about the hotel?

In [30]:
result = amenities_agent.invoke({"messages": [{"role": "user", "content": "What can I do without a booking?"}]})
print(get_output_text(result))

15:01:54 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
15:01:54 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
15:01:55 httpx INFO   HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
15:01:55 httpx INFO   HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
15:01:55 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using query str: walk-in amenities
15:01:55 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using query str: walk-in amenities
15:01:55 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using filters: [('booking_required', '==', 'False')]
15:01:55 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using filters: [('booking_required', '==', 'False')]
15:01:55 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using top_k: 4
15:01:55 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using top_k: 4
15:01:55 llama_index.vector_stores.redis.base INFO   Querying index Amenities with query (@booking_required:{False} @min_notice_hours:[-inf 0])=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
15:01:55 llama_index.vector_stores.redis.base INFO   Querying index Amenities with query (@booking_required:{False} @min_notice_hours:[-inf 0])=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
15:01:55 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['Amenities:AM000016', 'Amenities:AM000030', 'Amenities:AM000007', 'Amenities:AM000003']
15:01:55 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['Amenities:AM000016', 'Amenities:AM000030', 'Amenities:AM000007', 'Amenities:AM000003']
15:02:01 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
15:02:01 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Here are a few amenities I found that indicate **booking is not required**:

**Name:** Evening Dining
**Category:** Room Service
**Price (USD):** 65
**Duration (minutes):** 45
**Availability:** 8:00-20:00
**Booking required:** False
**Minimum notice (hours):** 0
**Description:** Indulge in the convenience of our Evening Dining, where 45 minutes of professional service presentation brings satisfies your gourmet cravings, providing perfect satisfaction.

**Name:** Private Babysitting
**Category:** Childcare Services
**Price (USD):** 100
**Duration (minutes):** 240
**Availability:** 6:00-22:00
**Booking required:** False
**Minimum notice (hours):** 0
**Description:** Give your children an amazing time with our Private Babysitting, where 240 minutes of interactive play sessions provides promotes social interaction, guaranteeing socially connected and happy.

**Name:** Aromatherapy Journey
**Category:** Spa Services
**Price (USD):** 150
**Duration (minutes):** 75
**Availability:** 6:00-22:00
**Booking required:** False
**Minimum notice (hours):** 0
**Description:** Experience pure relaxation with our Aromatherapy Journey, a 75-minute treatment designed to promote deep relaxation and healing. Our certified therapists use premium natural skincare products to precise pressure point therapy, leaving you feeling deeply relaxed and refreshed.

**Name:** Couples Massage Experience
**Category:** Spa Services
**Price (USD):** 280
**Duration (minutes):** 90
**Availability:** By appointment only
**Booking required:** False
**Minimum notice (hours):** 0
**Description:** Indulge in our signature Couples Massage Experience, where 90 minutes of expert care will melt away stress and tension. This treatment features therapeutic-grade materials and customized therapeutic approaches to provide rejuvenated and restored.

Is there any other information I can provide about the hotel?

In [31]:
result = amenities_agent.invoke({"messages": [{"role": "user", "content": "What can I see at your petting zoo?"}]})
print(get_output_text(result))

15:02:02 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
15:02:02 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
15:02:03 httpx INFO   HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
15:02:03 httpx INFO   HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
15:02:03 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using query str: petting zoo animals what can I see
15:02:03 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using query str: petting zoo animals what can I see
15:02:03 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using filters: []
15:02:03 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using filters: []
15:02:03 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using top_k: 4
15:02:03 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using top_k: 4
15:02:03 llama_index.vector_stores.redis.base INFO   Querying index Amenities with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
15:02:03 llama_index.vector_stores.redis.base INFO   Querying index Amenities with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
15:02:03 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['Amenities:AM000030', 'Amenities:AM000023', 'Amenities:AM000029', 'Amenities:AM000025']
15:02:03 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['Amenities:AM000030', 'Amenities:AM000023', 'Amenities:AM000029', 'Amenities:AM000025']
15:02:13 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
15:02:13 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
I looked up our amenities and couldn’t find any listing or details for a “petting zoo,” including what animals you can see; the closest related offerings I found are:

**Name:** Kids Club Session
**Category:** Childcare Services
**Price (USD):** 80
**Duration (minutes):** 180
**Availability:** 6:00-22:00
**Booking required:** True
**Minimum notice (hours):** 4
**Description:** Entrust your little ones to our Kids Club Session, a 180-minute program that promotes social interaction. Our certified caregivers use interactive play sessions, ensuring creatively stimulated.

**Name:** Private Babysitting
**Category:** Childcare Services
**Price (USD):** 100
**Duration (minutes):** 240
**Availability:** 6:00-22:00
**Booking required:** False
**Minimum notice (hours):** 0
**Description:** Give your children an amazing time with our Private Babysitting, where 240 minutes of interactive play sessions provides promotes social interaction, guaranteeing socially connected and happy.

**Name:** Magic Show
**Category:** Entertainment Services
**Price (USD):** 600
**Duration (minutes):** 60
**Availability:** By appointment only
**Booking required:** True
**Minimum notice (hours):** 24
**Description:** Let us enchant you with our Magic Show, where 60 minutes of state-of-the-art audiovisual systems creates transports you to another world, delivering filled with joy and wonder.

**Name:** Private Movie Screening
**Category:** Entertainment Services
**Price (USD):** 300
**Duration (minutes):** 180
**Availability:** 24/7
**Booking required:** True
**Minimum notice (hours):** 24
**Description:** Immerse yourself in our Private Movie Screening, a 180-minute entertainment experience that transports you to another world. Our professional team delivers professional performance delivery, ensuring filled with joy and wonder.

Is there any other information I can provide about the hotel?

### Services

I would like to combine this with amenities as the dataset columns are almost identical, but this set doesn't have availability information. In practice, I would just ask for this information, but I can't do that here, so I'm keeping them separate.

Connect to Redis Cloud

In [82]:
from llama_index.core import StorageContext, VectorStoreIndex
from llama_index.vector_stores.redis import RedisVectorStore
from redisvl.schema import IndexSchema

redis_conn_string = os.getenv("REDIS_URL")
schema = IndexSchema.from_dict(
    {
        "index": {"name": "Services", "prefix": "Services"},
        # customize fields that are indexed
        "fields": [
            # required fields for llamaindex
            {"type": "tag", "name": "id"},
            {"type": "tag", "name": "doc_id"},
            {"type": "text", "name": "text"},
            # custom fields for filtering
            {"type": "tag", "name": "service_type"},
            {"type": "numeric", "name": "price"},
            {"type": "numeric", "name": "duration"},
            {"type": "numeric", "name": "min_notice_hours"},
            {"type": "tag", "name": "department"},
            {"type": "tag", "name": "booking_required"},
            # custom vector field for bge-small-en-v1.5 embeddings
            {
                "type": "vector",
                "name": "vector",
                "attrs": {
                    "dims": 384,
                    "algorithm": "hnsw",
                    "distance_metric": "cosine",
                },
            },
        ],
    },
)
redis_client = Redis.from_url(redis_conn_string, decode_responses=True)
vector_store = RedisVectorStore(schema=schema, redis_client=redis_client, overwrite=True)
storage_context = StorageContext.from_defaults(vector_store=vector_store)

17:18:30 redisvl.index.index INFO   Index already exists, overwriting.
17:18:30 redisvl.index.index INFO   Index already exists, overwriting.

Add services information

In [116]:
df_services = pd.read_pickle("../data/pandas/services.pkl")
df_services

,service_type,name,description,duration_minutes,price,department,booking_required,min_notice_hours
service_id,,,,,,,,
SV000001,Spa Treatment,Spa Treatment - 120 min,Swedish massage for 120 minutes using Modern t...,120,264.98,Spa & Wellness,True,4
SV000002,Spa Treatment,Spa Treatment - 60 min,Luxurious 60-minute Deep Tissue treatment feat...,60,232.03,Spa & Wellness,True,4
SV000003,Spa Treatment,Spa Treatment - 120 min,Premium Deep Tissue experience for 120 minutes...,120,251.99,Spa & Wellness,True,24
SV000004,Spa Treatment,Spa Treatment - 90 min,Luxurious 90-minute Hot Stone treatment featur...,90,157.55,Spa & Wellness,True,1
SV000005,Personal Training,Personal Training - 60 min,Custom 60-minute HIIT workout emphasizing Core...,60,133.13,Fitness Center,True,4
SV000006,Personal Training,Personal Training - 30 min,Personalized HIIT training for 30 minutes targ...,30,138.75,Fitness Center,True,4
SV000007,Personal Training,Personal Training - 60 min,Personalized Functional Fitness training for 6...,60,82.20,Fitness Center,True,24
SV000008,Personal Training,Personal Training - 60 min,Custom 60-minute Strength Training workout emp...,60,143.70,Fitness Center,True,2
SV000009,Wellness Consultation,Wellness Consultation - 60 min,In-depth Wellness Strategy session for 60 minu...,60,94.86,Spa & Wellness,True,1
SV000010,Wellness Consultation,Wellness Consultation - 45 min,Comprehensive 45-minute Nutrition Planning ass...,45,109.60,Spa & Wellness,True,2
SV000011,Wellness Consultation,Wellness Consultation - 60 min,Comprehensive 60-minute Lifestyle Assessment a...,60,130.29,Spa & Wellness,True,4
SV000012,Wellness Consultation,Wellness Consultation - 45 min,In-depth Wellness Strategy session for 45 minu...,45,118.17,Spa & Wellness,True,1
SV000013,Massage Therapy,Massage Therapy - 30 min,30-minute Recovery massage using Trigger Point...,30,91.32,Spa & Wellness,True,24
SV000014,Massage Therapy,Massage Therapy - 90 min,Specialized Sports Massage therapy session for...,90,157.61,Spa & Wellness,True,24
SV000015,Massage Therapy,Massage Therapy - 60 min,Specialized Recovery therapy session for 60 mi...,60,159.75,Spa & Wellness,True,4
SV000016,Massage Therapy,Massage Therapy - 90 min,Targeted 90-minute Recovery treatment employin...,90,117.71,Spa & Wellness,True,1
SV000017,Fitness Assessment,Fitness Assessment - 60 min,Professional 60-minute Movement Screening anal...,60,116.08,Fitness Center,True,24
SV000018,Fitness Assessment,Fitness Assessment - 60 min,Professional 60-minute Comprehensive Fitness T...,60,88.23,Fitness Center,True,2
SV000019,Fitness Assessment,Fitness Assessment - 60 min,Detailed Movement Screening assessment for 60 ...,60,74.60,Fitness Center,True,24
SV000020,Fitness Assessment,Fitness Assessment - 60 min,Professional 60-minute Performance Evaluation ...,60,60.63,Fitness Center,True,4
SV000021,Group Fitness Class,Group Fitness Class - 45 min,Dynamic HIIT session for 45 minutes targeting ...,45,48.11,Fitness Center,True,24
SV000022,Group Fitness Class,Group Fitness Class - 60 min,Energetic 60-minute HIIT class focusing on Str...,60,43.88,Fitness Center,True,2
SV000023,Group Fitness Class,Group Fitness Class - 60 min,Energetic 60-minute Boot Camp class focusing o...,60,25.21,Fitness Center,True,4
SV000024,Group Fitness Class,Group Fitness Class - 45 min,Engaging 45-minute Pilates class emphasizing S...,45,30.93,Fitness Center,True,1
SV000025,Group Fitness Class,Group Fitness Class - 45 min,Engaging 45-minute Yoga class emphasizing Full...,45,40.18,Fitness Center,True,2

In [84]:
def get_services_nodes():
    nodes = []
    for id_, row in df_services.iterrows():
        main_text = "Name:" + row["name"] + "\n\nDescription:\n" + row["description"]
        metadata = {"service_type": row["service_type"],
                    "duration": row["duration_minutes"],
                    "price": row["price"],
                    "department": row["department"],
                    "booking_required": str(row["booking_required"]),
                    "min_notice_hours": row["min_notice_hours"]}
        node = TextNode(text=main_text, id_=id_, metadata=metadata)
        nodes.append(node)
    return nodes

nodes = get_services_nodes()

In [85]:
services_index = VectorStoreIndex(nodes=nodes, storage_context=storage_context)
retriever = services_index.as_retriever(similarity_top_k=4)

17:18:36 llama_index.vector_stores.redis.base INFO   Added 25 documents to index Services
17:18:36 llama_index.vector_stores.redis.base INFO   Added 25 documents to index Services

In [36]:
retriever.retrieve("I want to do some pilates.")

15:02:14 llama_index.vector_stores.redis.base INFO   Querying index Services with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
15:02:14 llama_index.vector_stores.redis.base INFO   Querying index Services with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
15:02:14 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['Services:SV000024', 'Services:SV000008', 'Services:SV000007', 'Services:SV000006']
15:02:14 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['Services:SV000024', 'Services:SV000008', 'Services:SV000007', 'Services:SV000006']

[NodeWithScore(node=TextNode(id_='SV000024', embedding=None, metadata={'service_type': 'Group Fitness Class', 'duration': 45, 'price': 30.93, 'department': 'Fitness Center', 'booking_required': 'True', 'min_notice_hours': 1}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Name:Group Fitness Class - 45 min\n\nDescription:\nEngaging 45-minute Pilates class emphasizing Strength. Group Motivation.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.668034553528),
 NodeWithScore(node=TextNode(id_='SV000008', embedding=None, metadata={'service_type': 'Personal Training', 'duration': 60, 'price': 143.7, 'department': 'Fitness Center', 'booking_required': 'True', 'min_notice_hours': 2}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Name:Personal Training - 60 min\n\nDescription:\nCustom 60-minute Strength Training workout emphasizing Full Body. Better Flexibility.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.5771924853320001),
 NodeWithScore(node=TextNode(id_='SV000007', embedding=None, metadata={'service_type': 'Personal Training', 'duration': 60, 'price': 82.2, 'department': 'Fitness Center', 'booking_required': 'True', 'min_notice_hours': 24}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Name:Personal Training - 60 min\n\nDescription:\nPersonalized Functional Fitness training for 60 minutes targeting Lower Body. Enhanced Endurance.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.570578694344),
 NodeWithScore(node=TextNode(id_='SV000006', embedding=None, metadata={'service_type': 'Personal Training', 'duration': 30, 'price': 138.75, 'department': 'Fitness Center', 'booking_required': 'True', 'min_notice_hours': 4}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Name:Personal Training - 30 min\n\nDescription:\nPersonalized HIIT training for 30 minutes targeting Lower Body. Improved Strength.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.5666863322260001)]

Setup and auto-retriever that filters over metadata

In [37]:
index_name = vector_store.index_name
service_types = redis_client.ft(index_name).tagvals("service_type")
print(f"service types = {service_types}")

service types = ['fitness assessment', 'group fitness class', 'massage therapy', 'personal training', 'spa treatment', 'wellness consultation']

In [117]:
from llama_index.core.retrievers import VectorIndexAutoRetriever
from llama_index.core.vector_stores.types import (
    FilterOperator,
    MetadataFilter,
    MetadataFilters,
    MetadataInfo,
    VectorStoreInfo,
)

services_store_info = VectorStoreInfo(
    content_info="Information about hotel services",
    metadata_info=[
        MetadataInfo(
            name="service_type",
            type="tag",
            description=f"The type of service provided, one of {service_types}",
        ),
        MetadataInfo(
            name="booking_required",
            type="tag",
            description="""Whether a booking is requried for the service, either 'True'
            or 'False'. 'False' does NOT imply min_notice_hours=0.""",
        ),
    ],
)

def _range_filters(
    *,
    min_price: float | None = None,
    max_price: float | None = None,
    min_notice_hours: int | None = None,
    max_notice_hours: int | None = None,
    min_duration_minutes: int | None = None,
    max_duration_minutes: int | None = None,
) -> MetadataFilters | None:
    filters: list[MetadataFilter] = []

    if min_price is not None:
        filters.append(MetadataFilter(key="price", operator=FilterOperator.GTE, value=float(min_price)))
    if max_price is not None:
        filters.append(MetadataFilter(key="price", operator=FilterOperator.LTE, value=float(max_price)))

    if min_notice_hours is not None:
        filters.append(MetadataFilter(key="min_notice_hours", operator=FilterOperator.GTE, value=int(min_notice_hours)))
    if max_notice_hours is not None:
        filters.append(MetadataFilter(key="min_notice_hours", operator=FilterOperator.LTE, value=int(max_notice_hours)))

    if min_duration_minutes is not None:
        filters.append(MetadataFilter(key="duration", operator=FilterOperator.GTE, value=int(min_duration_minutes)))
    if max_duration_minutes is not None:
        filters.append(MetadataFilter(key="duration", operator=FilterOperator.LTE, value=int(max_duration_minutes)))

    return MetadataFilters(filters=filters) if filters else None

In [118]:
from langchain.tools import tool

gpt_version = "gpt-5.2"
Settings.llm = OpenAI(gpt_version, temperature=0, reasoning={"effort": "medium"})

@tool(parse_docstring=True)
def query_services(
    query: str,
    min_price: float | None = None,
    max_price: float | None = None,
    min_notice_hours: int | None = None,
    max_notice_hours: int | None = None,
    min_duration_minutes: int | None = None,
    max_duration_minutes: int | None = None,
) -> list[RetrievalItem]:
    """Provide information about the hotel's services in response to a passed-in query.

    Supports optional range filtering on numeric fields.

    Args:
        query (string): The query string.
        min_price (float, optional): Minimum price (inclusive).
        max_price (float, optional): Maximum price (inclusive).
        min_notice_hours (int, optional): Minimum notice hours (inclusive).
        max_notice_hours (int, optional): Maximum notice hours (inclusive).
        min_duration_minutes (int, optional): Minimum duration in minutes (inclusive).
        max_duration_minutes (int, optional): Maximum duration in minutes (inclusive).

    Returns:
        list[RetrievalItem]: The retrieved results and their associated source, metadata, and RAG
        similarity score.

    """
    filters = _range_filters(
        min_price=min_price,
        max_price=max_price,
        min_notice_hours=min_notice_hours,
        max_notice_hours=max_notice_hours,
        min_duration_minutes=min_duration_minutes,
        max_duration_minutes=max_duration_minutes,
    )

    retriever = VectorIndexAutoRetriever(services_index, extra_filters=filters, vector_store_info=services_store_info, similarity_top_k=4)

    nodes = retriever.retrieve(query)

    return [RetrievalItem(source = "services",
                          metadata = dict(getattr(n, "metadata", {})),
                          text = getattr(n, "text", ""),
                          score =  getattr(n, "score", 0))
            for n in nodes]

In [40]:
from langchain.agents import create_agent
from langchain_openai import ChatOpenAI

SYSTEM_PROMPT = """You are a hotel information assistant. You must answer user questions only using information returned by the hotel services search tool.

**Core rules**
* Always use the tool to look up amenities relevant to the user's request before answering.
* Do not invent, guess, or infer details that are not explicitly present in tool results.
* If the user asks for something not found, say you couldn't find it and offer the closest relevant matches (if any).
* Your results are not exhaustive; do not claim completeness.
* Assume all prices are in USD unless the tool indicates otherwise.
* Do not mention "database," "RAG," "embeddings," or internal implementation. You may say you "looked it up" or "searched."

**Retrieval behavior**
* Convert the user's request into a search intent (service types, keywords, constraints like price/duration/availability).
* Prefer precision: return only services that clearly match the request.
* If the request is broad ("spa options"), return a small curated set (e.g., 3-8) that best represent the service type.
* If the request is narrow and no exact hit exists, return near matches and explain why they're the closest.

**Response requirements**
You may provide a once sentence introduction to the results. List the relevant services afterwards.
For each service you include, present **only** the fields you have from the tool, using this schema and order:

**Name:**
**Service type:**
**Department:**
**Price (USD):**
**Duration (minutes):**
**Booking required:**
**Minimum notice (hours):**
**Description:**

* If a field is missing from the tool output, write "Not specified."
* Do not add advice, policies, instructions, or booking steps unless the tool output explicitly contains them.
* Do not offer to perform actions (booking, calling, emailing, etc.).

**After answering**
End with exactly one question:
"Is there any other information I can provide about the hotel?"
"""

llm = ChatOpenAI(model=gpt_version, temperature=0, reasoning={"effort": "medium"})
services_agent = create_agent(model=llm, tools=[query_services], system_prompt=SYSTEM_PROMPT)

In [41]:
def get_output_text(query_result) -> str:
    last_result = query_result["messages"][-1]
    for c in last_result.content:
        if "text" in c:
            return c["text"]
    return ""

In [42]:
result = services_agent.invoke({"messages": [{"role": "user", "content": "I would like an hour long massage"}]})
print(get_output_text(result))

15:02:16 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
15:02:16 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
15:02:18 httpx INFO   HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
15:02:18 httpx INFO   HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
15:02:18 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using query str: massage
15:02:18 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using query str: massage
15:02:18 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using filters: []
15:02:18 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using filters: []
15:02:18 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using top_k: 4
15:02:18 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using top_k: 4
15:02:18 llama_index.vector_stores.redis.base INFO   Querying index Services with query (@duration:[60 +inf] @duration:[-inf 60])=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
15:02:18 llama_index.vector_stores.redis.base INFO   Querying index Services with query (@duration:[60 +inf] @duration:[-inf 60])=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
15:02:18 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['Services:SV000015', 'Services:SV000002', 'Services:SV000009', 'Services:SV000011']
15:02:18 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['Services:SV000015', 'Services:SV000002', 'Services:SV000009', 'Services:SV000011']
15:02:22 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
15:02:22 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Here are the hour-long options I found that match a massage request:

**Name:** Massage Therapy - 60 min
**Service type:** Massage Therapy
**Department:** Spa & Wellness
**Price (USD):** 159.75
**Duration (minutes):** 60
**Booking required:** True
**Minimum notice (hours):** 4
**Description:** Specialized Recovery therapy session for 60 minutes with Deep Tissue approach. Improved Mobility.

**Name:** Spa Treatment - 60 min
**Service type:** Spa Treatment
**Department:** Spa & Wellness
**Price (USD):** 232.03
**Duration (minutes):** 60
**Booking required:** True
**Minimum notice (hours):** 4
**Description:** Luxurious 60-minute Deep Tissue treatment featuring Herbal Products and Traditional methods. Improved Circulation.

Is there any other information I can provide about the hotel?

In [43]:
result = services_agent.invoke({"messages": [{"role": "user", "content": "What can I do for between $50 and $100?"}]})
print(get_output_text(result))

15:02:24 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
15:02:24 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
15:02:26 httpx INFO   HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
15:02:26 httpx INFO   HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
15:02:26 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using query str:
15:02:26 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using query str:
15:02:26 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using filters: []
15:02:26 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using filters: []
15:02:26 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using top_k: 10
15:02:26 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using top_k: 10
15:02:26 llama_index.vector_stores.redis.base INFO   Querying index Services with query (@price:[50.0 +inf] @price:[-inf 100.0]) RETURN 4 id doc_id text _node_content DIALECT 2 LIMIT 0 10
15:02:26 llama_index.vector_stores.redis.base INFO   Querying index Services with query (@price:[50.0 +inf] @price:[-inf 100.0]) RETURN 4 id doc_id text _node_content DIALECT 2 LIMIT 0 10
15:02:26 llama_index.vector_stores.redis.base INFO   Found 6 results for query with id ['Services:SV000007', 'Services:SV000009', 'Services:SV000013', 'Services:SV000018', 'Services:SV000019', 'Services:SV000020']
15:02:26 llama_index.vector_stores.redis.base INFO   Found 6 results for query with id ['Services:SV000007', 'Services:SV000009', 'Services:SV000013', 'Services:SV000018', 'Services:SV000019', 'Services:SV000020']
15:02:28 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
15:02:28 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
15:02:29 httpx INFO   HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
15:02:29 httpx INFO   HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
15:02:29 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using query str: service
15:02:29 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using query str: service
15:02:29 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using filters: []
15:02:29 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using filters: []
15:02:29 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using top_k: 4
15:02:29 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using top_k: 4
15:02:29 llama_index.vector_stores.redis.base INFO   Querying index Services with query (@price:[50.0 +inf] @price:[-inf 100.0])=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
15:02:29 llama_index.vector_stores.redis.base INFO   Querying index Services with query (@price:[50.0 +inf] @price:[-inf 100.0])=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
15:02:29 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['Services:SV000018', 'Services:SV000019', 'Services:SV000009', 'Services:SV000020']
15:02:29 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['Services:SV000018', 'Services:SV000019', 'Services:SV000009', 'Services:SV000020']
15:02:37 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
15:02:37 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Here are a few hotel services I found priced between **$50 and $100**:

**Name:** Fitness Assessment - 60 min
**Service type:** Fitness Assessment
**Department:** Fitness Center
**Price (USD):** 88.23
**Duration (minutes):** 60
**Booking required:** True
**Minimum notice (hours):** 2
**Description:** Professional 60-minute Comprehensive Fitness Test analyzing Strength Metrics. Progress Tracking.

**Name:** Fitness Assessment - 60 min
**Service type:** Fitness Assessment
**Department:** Fitness Center
**Price (USD):** 74.6
**Duration (minutes):** 60
**Booking required:** True
**Minimum notice (hours):** 24
**Description:** Detailed Movement Screening assessment for 60 minutes examining Cardio Capacity. Program Optimization.

**Name:** Wellness Consultation - 60 min
**Service type:** Wellness Consultation
**Department:** Spa & Wellness
**Price (USD):** 94.86
**Duration (minutes):** 60
**Booking required:** True
**Minimum notice (hours):** 1
**Description:** In-depth Wellness Strategy session for 60 minutes addressing Sleep Improvement. Personalized Plan.

**Name:** Fitness Assessment - 60 min
**Service type:** Fitness Assessment
**Department:** Fitness Center
**Price (USD):** 60.63
**Duration (minutes):** 60
**Booking required:** True
**Minimum notice (hours):** 4
**Description:** Professional 60-minute Performance Evaluation analyzing Overall Fitness. Program Optimization.

Is there any other information I can provide about the hotel?

### Combine into a single agent

For reranking. Passing along everything to the reranker and expecting the LLM to copy it all does not work well.

In [119]:
class RetrievalItemLite(BaseModel):
    source: str = Field(..., description="FAQ | amenities | services")
    item_id: str = Field(..., description="Stable identifier for this item")
    score: float = Field(..., description="Similarity score; higher is more relevant")

Re-define (or define for the first time for FAQ) query tools to return RetrievalItemLite

In [120]:
from langchain.tools import tool


@tool(parse_docstring=True)
def query_faq(query: str) -> list[RetrievalItemLite]:
    """Provide information about which FAQs are relevant to the passed-in query.

    Args:
        query (string): The query string.

    Returns:
        list[RetrievalItemLite]: The source, item id, and similarity score for each item

    """
    nodes = faq_retriever.retrieve(query)

    return [RetrievalItemLite(source = "FAQ",
                          item_id = getattr(n, "id_", ""),
                          score =  getattr(n, "score", 0))
            for n in nodes]

In [121]:
@tool(parse_docstring=True)
def query_amenities(
    query: str,
    min_price: float | None = None,
    max_price: float | None = None,
    min_notice_hours: int | None = None,
    max_notice_hours: int | None = None,
    min_duration_minutes: int | None = None,
    max_duration_minutes: int | None = None,
) -> list[RetrievalItemLite]:
    """Provide information about which amenities are relevant to the passed-in query.

    Supports optional range filtering on numeric fields.

    Args:
        query (string): The query string.
        min_price (float, optional): Minimum price (inclusive).
        max_price (float, optional): Maximum price (inclusive).
        min_notice_hours (int, optional): Minimum notice hours (inclusive).
        max_notice_hours (int, optional): Maximum notice hours (inclusive).
        min_duration_minutes (int, optional): Minimum duration in minutes (inclusive).
        max_duration_minutes (int, optional): Maximum duration in minutes (inclusive).

    Returns:
        list[RetrievalItemLite]: The source, item id, and similarity score for each item

    """
    filters = _range_filters(
        min_price=min_price,
        max_price=max_price,
        min_notice_hours=min_notice_hours,
        max_notice_hours=max_notice_hours,
        min_duration_minutes=min_duration_minutes,
        max_duration_minutes=max_duration_minutes,
    )

    amenities_retriever = VectorIndexAutoRetriever(
        amenities_index, extra_filters=filters, vector_store_info=amenities_store_info,
        similarity_top_k=4)

    nodes = amenities_retriever.retrieve(query)

    return [RetrievalItemLite(source = "amenities",
                          item_id = getattr(n, "id_", ""),
                          score =  getattr(n, "score", 0))
            for n in nodes]

In [122]:
@tool(parse_docstring=True)
def query_services(
    query: str,
    min_price: float | None = None,
    max_price: float | None = None,
    min_notice_hours: int | None = None,
    max_notice_hours: int | None = None,
    min_duration_minutes: int | None = None,
    max_duration_minutes: int | None = None,
) -> list[RetrievalItemLite]:
    """Provide information about which services are relevant to the passed-in query.

    Supports optional range filtering on numeric fields.

    Args:
        query (string): The query string.
        min_price (float, optional): Minimum price (inclusive).
        max_price (float, optional): Maximum price (inclusive).
        min_notice_hours (int, optional): Minimum notice hours (inclusive).
        max_notice_hours (int, optional): Maximum notice hours (inclusive).
        min_duration_minutes (int, optional): Minimum duration in minutes (inclusive).
        max_duration_minutes (int, optional): Maximum duration in minutes (inclusive).

    Returns:
        list[RetrievalItemLite]: The source, item id, and similarity score for each item

    """
    filters = _range_filters(
        min_price=min_price,
        max_price=max_price,
        min_notice_hours=min_notice_hours,
        max_notice_hours=max_notice_hours,
        min_duration_minutes=min_duration_minutes,
        max_duration_minutes=max_duration_minutes,
    )

    retriever = VectorIndexAutoRetriever(services_index, extra_filters=filters, vector_store_info=services_store_info, similarity_top_k=4)

    nodes = retriever.retrieve(query)

    return [RetrievalItemLite(source = "services",
                          item_id = getattr(n, "id_", ""),
                          score =  getattr(n, "score", 0))
            for n in nodes]

Reranker tool for returning combined top k results

In [123]:
import heapq

top_k = 4

class RerankInput(BaseModel):
    faq_results: list[RetrievalItemLite] = Field(..., description="Output from query_faq")
    amenities_results: list[RetrievalItemLite] = Field(..., description="Output from query_amenities")
    services_results: list[RetrievalItemLite] = Field(..., description="Output from query_services")

@tool(args_schema=RerankInput)
def reranker(
    faq_results: list[RetrievalItemLite],
    amenities_results: list[RetrievalItemLite],
    services_results: list[RetrievalItemLite],
    ) -> list[RetrievalItemLite]:
    """Rerank combined results from earlier tool calls according to similarity score.

    Args:
        faq_results (list[RetrievalItemLite]): The results of the call to query_faq
        amenities_results (list[RetrievalItemLite]): The results of the call to query_amenities
        services_results (list[RetrievalItemLite]): The results of the call to query_services

    Returns:
        list[RetrievalItemLite]: The top_k results

    """
    all_results = faq_results + amenities_results + services_results
    return heapq.nlargest(top_k, all_results, key=lambda x: x.score)

Retrieve the data that the LLM needs to put together a response

In [124]:
import json

class HydrateInput(BaseModel):
    items: list[RetrievalItemLite] = Field(..., description="Top items from reranker")

PREFIX_BY_SOURCE = {
    "faq": "FAQ",
    "amenities": "Amenities",   # use your actual prefix
    "services": "Services",     # matches your schema
}

@tool(args_schema=HydrateInput)
def hydrate_items(items: list[RetrievalItemLite]) -> list[RetrievalItem]:
    """Hydrate lite reranked items into full objects (text + metadata)."""
    out: list[RetrievalItem] = []
    for it in items:
        prefix = PREFIX_BY_SOURCE[it.source.lower()]
        data_list = redis_client.hmget(f"{prefix}:{it.item_id}",
                                       ["_node_content", "text"])

        # Fallback: if you can't docstore-get by node_id, you need a deterministic fetch strategy.
        # One common fallback is to store a stable 'doc_id' in metadata and filter retrieval by it.
        if data_list is None:
            error_str = f"Could not hydrate item_id={it.item_id} from source={it.source}."
            raise RuntimeError(error_str)

        data = json.loads(data_list[0])
        text = data_list[1]

        out.append(
            RetrievalItem(
                source=it.source,
                metadata=data["metadata"],
                text=text or "",
                score=it.score,
            ),
        )
    return out

Setup and prompt the LLM

In [127]:
from langchain.agents import create_agent
from langchain_openai import ChatOpenAI

SYSTEM_PROMPT = f"""You are a hotel information assistant. You answer user questions
only using information returned by the provided retrieval and reranking tools.

Available tools
- query_faq - retrieves up to {top_k} FAQ nodes
- query_amenities - retrieves up to {top_k} amenity nodes
- query_services - retrieves up to {top_k} service nodes
- reranker - requires THREE arguments:
  - faq_results: output list from query_faq
  - amenities_results: output list from query_amenities
  - services_results: output list from query_services
  It returns a list of the the top {top_k} nodes.
- hydrate_items - takes the list of top nodes and retrieves the associated text and metadata

Non-negotiable rules
- Always call all three retrieval tools for every user query.
- Always call the reranker after collecting retrieval results.
- The final results must come exclusively from the reranker's output.
- Do not invent, infer, or embellish information that is not explicitly present in retrieved nodes.
- Do not mention internal implementation details (RAG, embeddings, vector stores, scores, or node IDs).
- You may say you "looked it up" or "searched."
- Your answer is not exhaustive; never claim completeness.
- Do not offer to perform actions (booking, calling, emailing, etc.) unless explicitly stated in retrieved content.
- Assume prices are USD unless otherwise stated.

Mandatory workflow (must follow exactly)
1. Parse the user request into:
   - primary intent/topic
   - constraints (price, duration, hours, availability, booking, notice)
   - relevant keywords and synonyms
2. Query all three retrieval tools using the parsed intent.
3. Call reranker with named arguments exactly like:
   reranker(faq_results=<output of query_faq>,
            amenities_results=<output of query_amenities>,
            services_results=<output of query_services>).
4. Call hydrate_items with the top {top_k} nodes from the reranker.
5. Receive the final results (nodes with text and metadata).
6. Use only those nodes to construct the final response.
   - If the information in a node is irrelevant, exclude it.

De-duplication and conflicts
- If multiple reranked nodes convey the same information:
  - Merge them into a single entry without losing details.
- If reranked nodes conflict:
  - Present both facts clearly and without reconciliation unless the data explicitly resolves the conflict.

Response formatting
- You may provide a once sentence introduction to the results. List the relevant results afterwards.
- If an FAQ result is relevant to the user's query, place it at the top of the results.
- Present results in a clean, scannable format.
- Include only information explicitly present in the node.
- Place the field information to the right of the field heading.
- If a field is missing, write "Not specified."
- Do not add advice, policies, or instructions not present in the retrieved content.

Explicit formatting by type
- FAQ results should be presented as a one or two sentence response to the user's query.

- Amenity results must be formatted eactly as:
**<Name>**
  **Category:**
  **Price (USD):**
  **Duration (minutes):**
  **Availability:**
  **Booking required:**
  **Minimum notice (hours):**
  **Description:**

- Service results must be formatted exactly as:
**<Name>**
  **Service type:**
  **Department:**
  **Price (USD):**
  **Duration (minutes):**
  **Booking required:**
  **Minimum notice (hours):**
  **Description:**

Handling missing or weak matches
- If fewer than {top_k} reranked nodes are meaningfully relevant:
  - Return fewer results and clearly state what could not be found.
- If the user request is ambiguous:
  - Present the reranked results as-is.

Ending
After the response, end with exactly the following text:
"Is there any other information I can provide about the hotel? I can also help finding and booking a room."
"""

llm = ChatOpenAI(model=gpt_version, temperature=0, reasoning={"effort": "medium"})
combined_agent = create_agent(
    model=llm,
    tools=[query_faq, query_amenities, query_services, reranker, hydrate_items],
    system_prompt=SYSTEM_PROMPT,
    )

In [128]:
result = combined_agent.invoke({"messages": [{"role": "user", "content": "I want an hour long massage"}]})
print(get_output_text(result))

12:41:03 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
12:41:03 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
12:41:03 llama_index.vector_stores.redis.base INFO   Querying index FAQ with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
12:41:03 llama_index.vector_stores.redis.base INFO   Querying index FAQ with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
12:41:03 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['FAQ:FAQ000010', 'FAQ:FAQ000003', 'FAQ:FAQ000005', 'FAQ:FAQ000004']
12:41:03 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['FAQ:FAQ000010', 'FAQ:FAQ000003', 'FAQ:FAQ000005', 'FAQ:FAQ000004']
12:41:05 httpx INFO   HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
12:41:05 httpx INFO   HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
12:41:05 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using query str: massage 60 minutes hour long
12:41:05 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using query str: massage 60 minutes hour long
12:41:05 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using filters: []
12:41:05 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using filters: []
12:41:05 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using top_k: 4
12:41:05 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using top_k: 4
12:41:05 llama_index.vector_stores.redis.base INFO   Querying index Amenities with query (@duration:[60 +inf] @duration:[-inf 60])=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
12:41:05 llama_index.vector_stores.redis.base INFO   Querying index Amenities with query (@duration:[60 +inf] @duration:[-inf 60])=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
12:41:05 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['Amenities:AM000001', 'Amenities:AM000002', 'Amenities:AM000011', 'Amenities:AM000009']
12:41:05 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['Amenities:AM000001', 'Amenities:AM000002', 'Amenities:AM000011', 'Amenities:AM000009']
12:41:05 httpx INFO   HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
12:41:05 httpx INFO   HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
12:41:05 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using query str: massage 60 minutes hour long
12:41:05 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using query str: massage 60 minutes hour long
12:41:05 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using filters: []
12:41:05 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using filters: []
12:41:05 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using top_k: 4
12:41:05 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using top_k: 4
12:41:05 llama_index.vector_stores.redis.base INFO   Querying index Services with query (@duration:[60 +inf] @duration:[-inf 60])=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
12:41:05 llama_index.vector_stores.redis.base INFO   Querying index Services with query (@duration:[60 +inf] @duration:[-inf 60])=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
12:41:05 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['Services:SV000015', 'Services:SV000002', 'Services:SV000011', 'Services:SV000009']
12:41:05 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['Services:SV000015', 'Services:SV000002', 'Services:SV000011', 'Services:SV000009']
12:41:12 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
12:41:12 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
12:41:13 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
12:41:13 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
12:41:20 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
12:41:20 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Here are the 60-minute massage options I found:

**Massage Therapy - 60 min**
  **Service type:** Massage Therapy
  **Department:** Spa & Wellness
  **Price (USD):** 159.75
  **Duration (minutes):** 60
  **Booking required:** True
  **Minimum notice (hours):** 4
  **Description:** Specialized Recovery therapy session for 60 minutes with Deep Tissue approach. Improved Mobility.

**Swedish Massage**
  **Category:** Spa Services
  **Price (USD):** 120
  **Duration (minutes):** 60
  **Availability:** 24/7
  **Booking required:** True
  **Minimum notice (hours):** 2
  **Description:** Experience pure relaxation with our Swedish Massage, a 60-minute treatment designed to melt away stress and tension. Our certified therapists use premium natural skincare products to precise pressure point therapy, leaving you feeling renewed and revitalized.

**Deep Tissue Massage**
  **Category:** Spa Services
  **Price (USD):** 140
  **Duration (minutes):** 60
  **Availability:** 6:00-22:00
  **Booking required:** False
  **Minimum notice (hours):** 4
  **Description:** Indulge in our signature Deep Tissue Massage, where 60 minutes of expert care will melt away stress and tension. This treatment features natural skincare products and customized therapeutic approaches to provide rejuvenated and restored.

Is there any other information I can provide about the hotel? I can also help finding and booking a room.