Setup a Redis vector store that works with LlamaIndex for the FAQ, amenities, and services info.

I provide metadata information because it's useful to the user and LlamaIndex can have the LLM filter by it.

Load environment variables from .env file

In [21]:
import os

from dotenv import load_dotenv

load_dotenv()

True

For info on what's happening in the background

In [22]:
import logging
import sys

logging.basicConfig(stream=sys.stdout, level=logging.INFO)
logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))

The default number of items to return to the LLM

In [23]:
top_k = 4

Setup the embedding model

Use HuggingFaceEmbedding running locally because OpenAIEmbedding takes a long time to initialize.

In [24]:
from llama_index.core import Settings

# from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.embeddings.openai import OpenAIEmbedding
# from llama_index.embeddings.google_genai import GoogleGenAIEmbedding

In [25]:
Settings.embed_model = OpenAIEmbedding(model="text-embedding-3-small")
# Settings.embed_model = OpenAIEmbedding()
# Settings.embed_model = HuggingFaceEmbedding("BAAI/bge-small-en-v1.5")
# Settings.embed_model = GoogleGenAIEmbedding("gemini-embedding-001", dimensions=768)

### Typing for Retrievers

In [26]:
from typing import Any

from pydantic import BaseModel, Field


class RetrievalItem(BaseModel):
    source: str = Field(..., description="Which retriever produced this item: FAQ, amenities, or services")
    metadata: dict[str, Any] = Field(..., description="The metadata associated with the text.")
    text: str = Field(..., description="The item name and description")
    score: float = Field(..., description="Similarity score; higher is more relevant")

### FAQ

Connect to Redis Cloud

In [27]:
from llama_index.core import StorageContext, VectorStoreIndex
from llama_index.vector_stores.redis import RedisVectorStore
from redis import Redis
from redisvl.schema import IndexSchema

redis_conn_string = os.getenv("REDIS_URL")
faq_schema = IndexSchema.from_dict(
    {
        "index": {"name": "faq", "prefix": "faq"},
        # customize fields that are indexed
        "fields": [
            # required fields for llamaindex
            {"type": "tag", "name": "id"},
            {"type": "tag", "name": "doc_id"},
            {"type": "text", "name": "text"},
            # custom for metadata filtering
            {"type": "tag", "name": "category"},
            # custom vector field for text-embedding-3-small
            {
                "type": "vector",
                "name": "vector",
                "attrs": {
                    "dims": 1536,
                    "algorithm": "hnsw",
                    "distance_metric": "cosine",
                },
            },
        ],
    },
)
redis_client = Redis.from_url(redis_conn_string, decode_responses=True)
faq_vector_store = RedisVectorStore(schema=faq_schema, redis_client=redis_client, overwrite=True)
faq_storage_context = StorageContext.from_defaults(vector_store=faq_vector_store)

16:15:30 redisvl.index.index INFO   Index already exists, overwriting.
16:15:30 redisvl.index.index INFO   Index already exists, overwriting.
Index already exists, overwriting.

Load the FAQ

In [28]:
import pandas as pd

df_faq = pd.read_pickle("../data/pandas/faq_knowledge_base.pkl")  # noqa: S301
df_faq

,category,subcategory,question,answer,keywords,last_updated,helpful_votes,views
faq_id,,,,,,,,
FAQ000001,booking,reservations,How do I make a reservation?,You can make a reservation through our website...,"book, reserve, reservation, booking",2024-03-09,957,3813
FAQ000002,booking,check-in/out,What is the check-in/check-out time?,Check-in time is 3:00 PM and check-out time is...,"check in, check out, arrival, departure",2024-10-15,967,2793
FAQ000003,booking,modifications,Can I modify my booking?,"Yes, you can modify your booking through our w...","change, modify, update, edit",2024-12-05,443,1929
FAQ000004,booking,cancellations,What is the cancellation policy?,Free cancellation is available up to 48 hours ...,"cancel, refund, cancellation",2024-05-20,611,1300
FAQ000005,booking,special requests,Do you offer early check-in/late check-out?,"Subject to availability, early check-in and la...","early check-in, late check-out, extended stay",2024-12-18,239,3954
FAQ000006,amenities,facilities,What amenities are included?,"Our hotel offers complimentary Wi-Fi, fitness ...","amenities, facilities, services",2024-10-24,855,1860
FAQ000007,amenities,dining,Is breakfast included?,"Yes, breakfast is included with most room rate...","breakfast, dining, restaurant",2024-01-10,365,1943
FAQ000008,amenities,wellness,Do you have a fitness center?,"Yes, our fitness center is open 24/7 and featu...","fitness, gym, exercise",2024-10-05,988,1471
FAQ000009,amenities,business,Is there a swimming pool?,"Yes, we have both indoor and outdoor pools ope...","pool, swimming, recreation",2024-10-15,400,2881
FAQ000010,amenities,recreation,Do you offer spa services?,"Our full-service spa offers massages, facials,...","spa, wellness, treatments",2024-01-07,145,766
FAQ000011,services,room service,Is room service available?,Room service is available 24/7 with a full men...,"room service, dining, food",2024-04-05,708,2133
FAQ000012,services,housekeeping,Do you offer laundry service?,"Yes, same-day laundry and dry-cleaning service...","laundry, cleaning, housekeeping",2024-09-16,126,249
FAQ000013,services,concierge,Is there a business center?,Our business center is open 24/7 and offers co...,"business, work, office",2024-05-25,925,1604
FAQ000014,services,transportation,Do you provide airport transfers?,"Yes, we offer airport shuttle service for a fe...","airport, shuttle, transfer",2024-11-27,743,1621
FAQ000015,services,business,Is parking available?,We offer both self-parking and valet parking s...,"parking, valet, car",2024-02-03,721,1975
FAQ000016,policies,pet policy,What is your pet policy?,We welcome pets under 25 pounds for an additio...,"pets, animals, dogs, cats",2024-07-17,639,4327
FAQ000017,policies,smoking policy,Do you have smoking rooms?,All our rooms are non-smoking. Smoking is only...,"smoking, non-smoking, tobacco",2024-01-31,703,2992
FAQ000018,policies,payment policy,What forms of payment do you accept?,"We accept all major credit cards, debit cards,...","payment, credit card, cash",2024-10-30,799,2778
FAQ000019,policies,age requirements,Is there a minimum age to check in?,Guests must be 18 or older to check in. Valid ...,"age, check-in, requirements",2024-01-09,662,4150
FAQ000020,policies,luggage policy,What is your luggage storage policy?,Complimentary luggage storage is available bef...,"luggage, storage, bags",2024-06-20,127,213

Prepare data for storage

In [29]:
from llama_index.core.schema import TextNode


def get_faq_nodes() -> list:
    nodes = []
    for id_, row in df_faq.iterrows():
        main_text = "Question:\n" + row["question"] + "\n\nAnswer:\n" + row["answer"]
        metadata = {"category": row["category"],
                    "subcategory": row["subcategory"],
                    "keywords": row["keywords"],
                    "last_updated": row["last_updated"]}
        node = TextNode(text=main_text, id_=id_, metadata=metadata)
        nodes.append(node)
    return nodes

faq_nodes = get_faq_nodes()

Store in vector store

In [30]:
faq_index = VectorStoreIndex(nodes=faq_nodes, storage_context=faq_storage_context)

16:15:31 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:15:31 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:15:31 llama_index.vector_stores.redis.base INFO   Added 20 documents to index faq
16:15:31 llama_index.vector_stores.redis.base INFO   Added 20 documents to index faq
Added 20 documents to index faq

Setup and test retrieval

In [31]:
faq_retriever = faq_index.as_retriever(similarity_top_k=top_k)

In [32]:
faq_retriever.retrieve("Is there a place to swim?")

16:15:31 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:15:31 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:15:31 llama_index.vector_stores.redis.base INFO   Querying index faq with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
16:15:31 llama_index.vector_stores.redis.base INFO   Querying index faq with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
Querying index faq with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
16:15:31 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['faq:FAQ000009', 'faq:FAQ000008', 'faq:FAQ000006', 'faq:FAQ000010']
16:15:31 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['faq:FAQ000009', 'faq:FAQ000008', 'faq:FAQ000006', 'faq:FAQ000010']
Found 4 results for query with id ['faq:FAQ000009', 'faq:FAQ000008', 'faq:FAQ000006', 'faq:FAQ000010']

[NodeWithScore(node=TextNode(id_='FAQ000009', embedding=None, metadata={'category': 'amenities', 'subcategory': 'business', 'keywords': 'pool, swimming, recreation', 'last_updated': '2024-10-15'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Question:\nIs there a swimming pool?\n\nAnswer:\nYes, we have both indoor and outdoor pools open from 6:00 AM to 10:00 PM.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.578024506569),
 NodeWithScore(node=TextNode(id_='FAQ000008', embedding=None, metadata={'category': 'amenities', 'subcategory': 'wellness', 'keywords': 'fitness, gym, exercise', 'last_updated': '2024-10-05'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Question:\nDo you have a fitness center?\n\nAnswer:\nYes, our fitness center is open 24/7 and features modern equipment and free weights.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.35589855909300006),
 NodeWithScore(node=TextNode(id_='FAQ000006', embedding=None, metadata={'category': 'amenities', 'subcategory': 'facilities', 'keywords': 'amenities, facilities, services', 'last_updated': '2024-10-24'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Question:\nWhat amenities are included?\n\nAnswer:\nOur hotel offers complimentary Wi-Fi, fitness center, pool, spa, restaurant, and 24-hour room service.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.32676136493700003),
 NodeWithScore(node=TextNode(id_='FAQ000010', embedding=None, metadata={'category': 'amenities', 'subcategory': 'recreation', 'keywords': 'spa, wellness, treatments', 'last_updated': '2024-01-07'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Question:\nDo you offer spa services?\n\nAnswer:\nOur full-service spa offers massages, facials, and body treatments. Advance booking is recommended.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.32547163963299997)]

Setup and auto-retriever that filters over metadata.

Whether it works depends heavily on the model chosen. gpt-5-mini causes an error sometimes. I won't include this in the production code for the FAQ as there's little point.

In [33]:
faq_index_name = faq_vector_store.index_name
categories = redis_client.ft(faq_index_name).tagvals("category")
print(categories)

['amenities', 'booking', 'policies', 'services']

In [39]:
from llama_index.core.retrievers import VectorIndexAutoRetriever
from llama_index.core.vector_stores.types import MetadataInfo, VectorStoreInfo
from llama_index.llms.openai import OpenAI

Settings.llm = OpenAI(model="gpt-5", temperature=0.0, reasoning={"effort": "medium"})

faq_store_info = VectorStoreInfo(
    content_info="FAQs and their answers for the hotel",
    metadata_info=[
        MetadataInfo(
            name="category",
            type="tag",
            description=f"Category of the FAQ, one of {categories}",
        ),
    ],
)
faq_retriever=VectorIndexAutoRetriever(faq_index, vector_store_info=faq_store_info, similarity_top_k=top_k)

The auto-retriever works well with gpt-5, but it's slow. gpt-5.1 and gpt-5.2 often don't filter at all. They might understand that multiple categories can apply, so there's no point in picking one. In production, I just use a regular retriever.

In [40]:
faq_retriever.retrieve("Is there a place to swim?")

16:17:29 httpx INFO   HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
16:17:29 httpx INFO   HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
16:17:29 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using query str: swimming pool
16:17:29 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using query str: swimming pool
Using query str: swimming pool
16:17:29 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using filters: []
16:17:29 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using filters: []
Using filters: []
16:17:29 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using top_k: 4
16:17:29 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using top_k: 4
Using top_k: 4
16:17:30 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:17:30 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:17:30 llama_index.vector_stores.redis.base INFO   Querying index faq with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
16:17:30 llama_index.vector_stores.redis.base INFO   Querying index faq with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
Querying index faq with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
16:17:30 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['faq:FAQ000009', 'faq:FAQ000006', 'faq:FAQ000008', 'faq:FAQ000010']
16:17:30 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['faq:FAQ000009', 'faq:FAQ000006', 'faq:FAQ000008', 'faq:FAQ000010']
Found 4 results for query with id ['faq:FAQ000009', 'faq:FAQ000006', 'faq:FAQ000008', 'faq:FAQ000010']

[NodeWithScore(node=TextNode(id_='FAQ000009', embedding=None, metadata={'category': 'amenities', 'subcategory': 'business', 'keywords': 'pool, swimming, recreation', 'last_updated': '2024-10-15'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Question:\nIs there a swimming pool?\n\nAnswer:\nYes, we have both indoor and outdoor pools open from 6:00 AM to 10:00 PM.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.583223819733),
 NodeWithScore(node=TextNode(id_='FAQ000006', embedding=None, metadata={'category': 'amenities', 'subcategory': 'facilities', 'keywords': 'amenities, facilities, services', 'last_updated': '2024-10-24'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Question:\nWhat amenities are included?\n\nAnswer:\nOur hotel offers complimentary Wi-Fi, fitness center, pool, spa, restaurant, and 24-hour room service.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.323239386082),
 NodeWithScore(node=TextNode(id_='FAQ000008', embedding=None, metadata={'category': 'amenities', 'subcategory': 'wellness', 'keywords': 'fitness, gym, exercise', 'last_updated': '2024-10-05'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Question:\nDo you have a fitness center?\n\nAnswer:\nYes, our fitness center is open 24/7 and features modern equipment and free weights.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.316538929939),
 NodeWithScore(node=TextNode(id_='FAQ000010', embedding=None, metadata={'category': 'amenities', 'subcategory': 'recreation', 'keywords': 'spa, wellness, treatments', 'last_updated': '2024-01-07'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Question:\nDo you offer spa services?\n\nAnswer:\nOur full-service spa offers massages, facials, and body treatments. Advance booking is recommended.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.277807176113)]

In [41]:
faq_retriever.retrieve("What's the policy on smoking?")

16:17:48 httpx INFO   HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
16:17:48 httpx INFO   HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
16:17:48 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using query str: smoking
16:17:48 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using query str: smoking
Using query str: smoking
16:17:48 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using filters: [('category', '==', 'policies')]
16:17:48 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using filters: [('category', '==', 'policies')]
Using filters: [('category', '==', 'policies')]
16:17:48 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using top_k: 4
16:17:48 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using top_k: 4
Using top_k: 4
16:17:48 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:17:48 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:17:48 llama_index.vector_stores.redis.base INFO   Querying index faq with query @category:{policies}=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
16:17:48 llama_index.vector_stores.redis.base INFO   Querying index faq with query @category:{policies}=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
Querying index faq with query @category:{policies}=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
16:17:48 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['faq:FAQ000017', 'faq:FAQ000016', 'faq:FAQ000019', 'faq:FAQ000018']
16:17:48 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['faq:FAQ000017', 'faq:FAQ000016', 'faq:FAQ000019', 'faq:FAQ000018']
Found 4 results for query with id ['faq:FAQ000017', 'faq:FAQ000016', 'faq:FAQ000019', 'faq:FAQ000018']

[NodeWithScore(node=TextNode(id_='FAQ000017', embedding=None, metadata={'category': 'policies', 'subcategory': 'smoking policy', 'keywords': 'smoking, non-smoking, tobacco', 'last_updated': '2024-01-31'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Question:\nDo you have smoking rooms?\n\nAnswer:\nAll our rooms are non-smoking. Smoking is only permitted in designated outdoor areas.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.449291229248),
 NodeWithScore(node=TextNode(id_='FAQ000016', embedding=None, metadata={'category': 'policies', 'subcategory': 'pet policy', 'keywords': 'pets, animals, dogs, cats', 'last_updated': '2024-07-17'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Question:\nWhat is your pet policy?\n\nAnswer:\nWe welcome pets under 25 pounds for an additional fee. Please notify us in advance.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.10108399391199996),
 NodeWithScore(node=TextNode(id_='FAQ000019', embedding=None, metadata={'category': 'policies', 'subcategory': 'age requirements', 'keywords': 'age, check-in, requirements', 'last_updated': '2024-01-09'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Question:\nIs there a minimum age to check in?\n\nAnswer:\nGuests must be 18 or older to check in. Valid ID required.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.10092842578899996),
 NodeWithScore(node=TextNode(id_='FAQ000018', embedding=None, metadata={'category': 'policies', 'subcategory': 'payment policy', 'keywords': 'payment, credit card, cash', 'last_updated': '2024-10-30'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Question:\nWhat forms of payment do you accept?\n\nAnswer:\nWe accept all major credit cards, debit cards, and cash with a security deposit.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.09526771307000004)]

### Amenities

Connect to Redis Cloud

In [42]:
from llama_index.core import StorageContext, VectorStoreIndex
from llama_index.vector_stores.redis import RedisVectorStore
from redis import Redis
from redisvl.schema import IndexSchema

redis_conn_string = os.getenv("REDIS_URL")
amenities_schema = IndexSchema.from_dict(
    {
        "index": {"name": "amenities", "prefix": "amenities"},
        # customize fields that are indexed
        "fields": [
            # required fields for llamaindex
            {"type": "tag", "name": "id"},
            {"type": "tag", "name": "doc_id"},
            {"type": "text", "name": "text"},
            # custom fields for filtering
            {"type": "tag", "name": "category"},
            {"type": "numeric", "name": "price"},
            {"type": "numeric", "name": "duration"},
            {"type": "numeric", "name": "min_notice_hours"},
            {"type": "tag", "name": "booking_required"},
            # custom vector field for text-embedding-3-small embeddings
            {
                "type": "vector",
                "name": "vector",
                "attrs": {
                    "dims": 1536,
                    "algorithm": "hnsw",
                    "distance_metric": "cosine",
                },
            },
        ],
    },
)
redis_client = Redis.from_url(redis_conn_string, decode_responses=True)
amenities_vector_store = RedisVectorStore(schema=amenities_schema, redis_client=redis_client, overwrite=True)
amenities_storage_context = StorageContext.from_defaults(vector_store=amenities_vector_store)

16:18:10 redisvl.index.index INFO   Index already exists, overwriting.
16:18:10 redisvl.index.index INFO   Index already exists, overwriting.
Index already exists, overwriting.

Add amenity information

In [43]:
import pandas as pd

df_amenities = pd.read_pickle("../data/pandas/amenities.pkl")  # noqa: S301
df_amenities.head()

,category,name,price,duration,description,availability,booking_required,min_notice_hours
amenity_id,,,,,,,,
AM000001,Spa Services,Swedish Massage,120,60,Experience pure relaxation with our Swedish Ma...,24/7,True,2
AM000002,Spa Services,Deep Tissue Massage,140,60,"Indulge in our signature Deep Tissue Massage, ...",6:00-22:00,False,4
AM000003,Spa Services,Couples Massage Experience,280,90,Indulge in our signature Couples Massage Exper...,By appointment only,False,0
AM000004,Spa Services,Hot Stone Therapy,160,90,Experience pure relaxation with our Hot Stone ...,6:00-22:00,False,1
AM000005,Spa Services,Luxury Facial Treatment,180,90,Indulge in our signature Luxury Facial Treatme...,24/7,False,24

Prepare data for storage

In [44]:
from llama_index.core.schema import TextNode


def get_amenities_nodes() -> list[TextNode]:
    nodes = []
    for id_, row in df_amenities.iterrows():
        main_text = "Name:" + row["name"] + "\n\nDescription:\n" + row["description"]
        metadata = {"category": row["category"],
                    "price": row["price"],
                    "duration": row["duration"],
                    "availability": row["availability"],
                    "booking_required": str(row["booking_required"]),
                    "min_notice_hours": row["min_notice_hours"]}
        node = TextNode(text=main_text, id_=id_, metadata=metadata)
        nodes.append(node)
    return nodes

amenities_nodes = get_amenities_nodes()

Store in vector store, setup retriever

In [45]:
amenities_index = VectorStoreIndex(nodes=amenities_nodes, storage_context=amenities_storage_context)
amenities_retriever = amenities_index.as_retriever(similarity_top_k=top_k)

16:18:11 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:18:11 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:18:11 llama_index.vector_stores.redis.base INFO   Added 34 documents to index amenities
16:18:11 llama_index.vector_stores.redis.base INFO   Added 34 documents to index amenities
Added 34 documents to index amenities

In [46]:
amenities_retriever.retrieve("Can I get a massage?")

16:18:12 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:18:12 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:18:12 llama_index.vector_stores.redis.base INFO   Querying index amenities with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
16:18:12 llama_index.vector_stores.redis.base INFO   Querying index amenities with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
Querying index amenities with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
16:18:12 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['amenities:AM000002', 'amenities:AM000003', 'amenities:AM000001', 'amenities:AM000007']
16:18:12 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['amenities:AM000002', 'amenities:AM000003', 'amenities:AM000001', 'amenities:AM000007']
Found 4 results for query with id ['amenities:AM000002', 'amenities:AM000003', 'amenities:AM000001', 'amenities:AM000007']

[NodeWithScore(node=TextNode(id_='AM000002', embedding=None, metadata={'category': 'Spa Services', 'price': 140, 'duration': 60, 'availability': '6:00-22:00', 'booking_required': 'False', 'min_notice_hours': 4}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Name:Deep Tissue Massage\n\nDescription:\nIndulge in our signature Deep Tissue Massage, where 60 minutes of expert care will melt away stress and tension. This treatment features natural skincare products and customized therapeutic approaches to provide rejuvenated and restored.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.482555985451),
 NodeWithScore(node=TextNode(id_='AM000003', embedding=None, metadata={'category': 'Spa Services', 'price': 280, 'duration': 90, 'availability': 'By appointment only', 'booking_required': 'False', 'min_notice_hours': 0}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Name:Couples Massage Experience\n\nDescription:\nIndulge in our signature Couples Massage Experience, where 90 minutes of expert care will melt away stress and tension. This treatment features therapeutic-grade materials and customized therapeutic approaches to provide rejuvenated and restored.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.47944486141200005),
 NodeWithScore(node=TextNode(id_='AM000001', embedding=None, metadata={'category': 'Spa Services', 'price': 120, 'duration': 60, 'availability': '24/7', 'booking_required': 'True', 'min_notice_hours': 2}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Name:Swedish Massage\n\nDescription:\nExperience pure relaxation with our Swedish Massage, a 60-minute treatment designed to melt away stress and tension. Our certified therapists use premium natural skincare products to precise pressure point therapy, leaving you feeling renewed and revitalized.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.470647752285),
 NodeWithScore(node=TextNode(id_='AM000007', embedding=None, metadata={'category': 'Spa Services', 'price': 150, 'duration': 75, 'availability': '6:00-22:00', 'booking_required': 'False', 'min_notice_hours': 0}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Name:Aromatherapy Journey\n\nDescription:\nExperience pure relaxation with our Aromatherapy Journey, a 75-minute treatment designed to promote deep relaxation and healing. Our certified therapists use premium natural skincare products to precise pressure point therapy, leaving you feeling deeply relaxed and refreshed.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.44103193283099995)]

Setup and filters over metadata. Originally used auto-retriever, but that's an over-complication. The main reason to use it is for category filtering, but the category to use isn't always obvious, so I just dropped that in the end. The Redis API also doesn't properly cast datatypes, so the auto-retriever failed when used over things like the price, so I had to setup those manually anyway.

In [47]:

from llama_index.core.vector_stores.types import (
    FilterOperator,
    MetadataFilter,
    MetadataFilters,
)


def _range_filters(  # noqa: PLR0913
    *,
    booking_required: bool | None = None,
    min_price: float | None = None,
    max_price: float | None = None,
    min_notice_hours: int | None = None,
    max_notice_hours: int | None = None,
    min_duration_minutes: int | None = None,
    max_duration_minutes: int | None = None,
) -> MetadataFilters | None:
    filters: list[MetadataFilter | MetadataFilters] = []

    if booking_required is not None:
        filters.append(MetadataFilter(key="booking_required", operator=FilterOperator.EQ,
                                      value="True" if booking_required else "False"))

    if min_price is not None:
        filters.append(MetadataFilter(key="price", operator=FilterOperator.GTE, value=float(min_price)))
    if max_price is not None:
        filters.append(MetadataFilter(key="price", operator=FilterOperator.LTE, value=float(max_price)))

    if min_notice_hours is not None:
        filters.append(MetadataFilter(key="min_notice_hours", operator=FilterOperator.GTE, value=int(min_notice_hours)))
    if max_notice_hours is not None:
        filters.append(MetadataFilter(key="min_notice_hours", operator=FilterOperator.LTE, value=int(max_notice_hours)))

    if min_duration_minutes is not None:
        filters.append(MetadataFilter(key="duration", operator=FilterOperator.GTE, value=int(min_duration_minutes)))
    if max_duration_minutes is not None:
        filters.append(MetadataFilter(key="duration", operator=FilterOperator.LTE, value=int(max_duration_minutes)))

    return MetadataFilters(filters=filters) if filters else None

In [48]:
from langchain.tools import tool
from langchain_openai import ChatOpenAI
from llama_index.core.retrievers import VectorIndexRetriever


@tool(parse_docstring=True)
def query_amenities(  # noqa: PLR0913
    query: str,
    booking_required: bool | None = None,  # noqa: FBT001
    min_price: float | None = None,
    max_price: float | None = None,
    min_notice_hours: int | None = None,
    max_notice_hours: int | None = None,
    min_duration_minutes: int | None = None,
    max_duration_minutes: int | None = None,
) -> list[RetrievalItem]:
    """Provide information about the hotel amenities in response to a passed-in query.

    Supports optional range filtering on numeric fields.

    Args:
        query (string): The query string.
        booking_required: Restrict results to booking_required==True/False.
        min_price (float, optional): Minimum price (inclusive).
        max_price (float, optional): Maximum price (inclusive).
        min_notice_hours (int, optional): Minimum notice hours (inclusive).
        max_notice_hours (int, optional): Maximum notice hours (inclusive).
        min_duration_minutes (int, optional): Minimum duration in minutes (inclusive).
        max_duration_minutes (int, optional): Maximum duration in minutes (inclusive).

    Returns:
        list[RetrievalItem]: The retrieved results and their associated source,
        metadata, and RAG similarity score.

    """
    filters = _range_filters(
        booking_required=booking_required,
        min_price=min_price,
        max_price=max_price,
        min_notice_hours=min_notice_hours,
        max_notice_hours=max_notice_hours,
        min_duration_minutes=min_duration_minutes,
        max_duration_minutes=max_duration_minutes,
    )

    amenities_retriever = VectorIndexRetriever(
        index=amenities_index, filters=filters, similarity_top_k=top_k)

    nodes = amenities_retriever.retrieve(query)

    return [RetrievalItem(source = "amenities",
                          metadata = dict(getattr(n, "metadata", {})),
                          text = getattr(n, "text", ""),
                          score =  getattr(n, "score", 0))
            for n in nodes]

In [49]:
from langchain.agents import create_agent

SYSTEM_PROMPT = """You are a hotel information assistant. You must answer user questions only using information returned by the hotel amenities search tool.

**Core rules**
* Always use the tool to look up amenities relevant to the user's request before answering.
* Do not invent, guess, or infer details that are not explicitly present in tool results.
* If the user asks for something not found, say you couldn't find it and offer the closest relevant matches (if any).
* Your results are not exhaustive; do not claim completeness.
* Assume all prices are in USD unless the tool indicates otherwise.
* Do not mention "database," "RAG," "embeddings," or internal implementation. You may say you "looked it up" or "searched."

**Retrieval behavior**
* Convert the user's request into a search intent (categories, keywords, constraints like price/duration/availability).
* Prefer precision: return only amenities that clearly match the request.
* If the request is broad ("spa options"), return a small curated set (e.g., 3-8) that best represent the category.
* If the request is narrow and no exact hit exists, return near matches and explain why they're the closest.

**Response requirements**
You may provide a once sentence introduction to the results. List the relevant amenities afterwards.
For each amenity you include, present **only** the fields you have from the tool, using this schema and order:

**Name:**
**Category:**
**Price (USD):**
**Duration (minutes):**
**Availability:**
**Booking required:**
**Minimum notice (hours):**
**Description:**

* If a field is missing from the tool output, write "Not specified."
* Do not add advice, policies, instructions, or booking steps unless the tool output explicitly contains them.
* Do not offer to perform actions (booking, calling, emailing, etc.).

**After answering**
End with exactly one question:
"Is there any other information I can provide about the hotel?"
"""

gpt_version="gpt-5.2"
amenities_llm = ChatOpenAI(model=gpt_version, temperature=0, reasoning={"effort": "medium"})
amenities_agent = create_agent(model=amenities_llm, tools=[query_amenities], system_prompt=SYSTEM_PROMPT)

In [50]:
def get_output_text(query_result) -> str:
    last_result = query_result["messages"][-1]
    for c in last_result.content:
        if "text" in c:
            return c["text"]
    return ""

gpt-5.1 keeps listing the Private Pilates Session in this test. gpt-5.2 almost never does.

In [51]:
result = amenities_agent.invoke({"messages": [{"role": "user", "content": "I would like an hour long massage"}]})
print(get_output_text(result))

16:18:21 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
16:18:21 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
16:18:22 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:18:22 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:18:22 llama_index.vector_stores.redis.base INFO   Querying index amenities with query (@duration:[55 +inf] @duration:[-inf 65])=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
16:18:22 llama_index.vector_stores.redis.base INFO   Querying index amenities with query (@duration:[55 +inf] @duration:[-inf 65])=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
Querying index amenities with query (@duration:[55 +inf] @duration:[-inf 65])=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
16:18:22 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['amenities:AM000002', 'amenities:AM000001', 'amenities:AM000009', 'amenities:AM000011']
16:18:22 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['amenities:AM000002', 'amenities:AM000001', 'amenities:AM000009', 'amenities:AM000011']
Found 4 results for query with id ['amenities:AM000002', 'amenities:AM000001', 'amenities:AM000009', 'amenities:AM000011']
16:18:27 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
16:18:27 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Here are the hotel’s hour-long massage options I found:

**Name:** Deep Tissue Massage
**Category:** Spa Services
**Price (USD):** 140
**Duration (minutes):** 60
**Availability:** 6:00-22:00
**Booking required:** False
**Minimum notice (hours):** 4
**Description:** Indulge in our signature Deep Tissue Massage, where 60 minutes of expert care will melt away stress and tension. This treatment features natural skincare products and customized therapeutic approaches to provide rejuvenated and restored.

**Name:** Swedish Massage
**Category:** Spa Services
**Price (USD):** 120
**Duration (minutes):** 60
**Availability:** 24/7
**Booking required:** True
**Minimum notice (hours):** 2
**Description:** Experience pure relaxation with our Swedish Massage, a 60-minute treatment designed to melt away stress and tension. Our certified therapists use premium natural skincare products to precise pressure point therapy, leaving you feeling renewed and revitalized.

Is there any other information I can provide about the hotel?

In [52]:
result = amenities_agent.invoke({"messages": [{"role": "user", "content": "What can my kids do for a couple of hours?"}]})
print(get_output_text(result))

16:18:32 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
16:18:32 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
16:18:33 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:18:33 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:18:33 llama_index.vector_stores.redis.base INFO   Querying index amenities with query (@duration:[90 +inf] @duration:[-inf 180])=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
16:18:33 llama_index.vector_stores.redis.base INFO   Querying index amenities with query (@duration:[90 +inf] @duration:[-inf 180])=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
Querying index amenities with query (@duration:[90 +inf] @duration:[-inf 180])=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
16:18:33 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:18:33 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:18:33 llama_index.vector_stores.redis.base INFO   Querying index amenities with query (@duration:[90 +inf] @duration:[-inf 180])=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
16:18:33 llama_index.vector_stores.redis.base INFO   Querying index amenities with query (@duration:[90 +inf] @duration:[-inf 180])=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
Querying index amenities with query (@duration:[90 +inf] @duration:[-inf 180])=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
16:18:33 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['amenities:AM000029', 'amenities:AM000031', 'amenities:AM000023', 'amenities:AM000027']
16:18:33 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['amenities:AM000029', 'amenities:AM000031', 'amenities:AM000023', 'amenities:AM000027']
16:18:33 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
Found 4 results for query with id ['amenities:AM000029', 'amenities:AM000031', 'amenities:AM000023', 'amenities:AM000027']
16:18:33 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:18:33 llama_index.vector_stores.redis.base INFO   Querying index amenities with query (@duration:[90 +inf] @duration:[-inf 180])=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
16:18:33 llama_index.vector_stores.redis.base INFO   Querying index amenities with query (@duration:[90 +inf] @duration:[-inf 180])=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
Querying index amenities with query (@duration:[90 +inf] @duration:[-inf 180])=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
16:18:33 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['amenities:AM000017', 'amenities:AM000023', 'amenities:AM000024', 'amenities:AM000029']
16:18:33 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['amenities:AM000017', 'amenities:AM000023', 'amenities:AM000024', 'amenities:AM000029']
Found 4 results for query with id ['amenities:AM000017', 'amenities:AM000023', 'amenities:AM000024', 'amenities:AM000029']
16:18:33 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['amenities:AM000029', 'amenities:AM000031', 'amenities:AM000024', 'amenities:AM000023']
16:18:33 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['amenities:AM000029', 'amenities:AM000031', 'amenities:AM000024', 'amenities:AM000023']
Found 4 results for query with id ['amenities:AM000029', 'amenities:AM000031', 'amenities:AM000024', 'amenities:AM000023']
16:18:33 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:18:33 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:18:33 llama_index.vector_stores.redis.base INFO   Querying index amenities with query (@duration:[90 +inf] @duration:[-inf 180])=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
16:18:33 llama_index.vector_stores.redis.base INFO   Querying index amenities with query (@duration:[90 +inf] @duration:[-inf 180])=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
Querying index amenities with query (@duration:[90 +inf] @duration:[-inf 180])=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
16:18:33 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['amenities:AM000029', 'amenities:AM000031', 'amenities:AM000003', 'amenities:AM000023']
16:18:33 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['amenities:AM000029', 'amenities:AM000031', 'amenities:AM000003', 'amenities:AM000023']
Found 4 results for query with id ['amenities:AM000029', 'amenities:AM000031', 'amenities:AM000003', 'amenities:AM000023']
16:18:40 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
16:18:40 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Here are on-site options I found that are specifically geared toward kids and last about a couple of hours:

**Name:** Kids Club Session
**Category:** Childcare Services
**Price (USD):** 80
**Duration (minutes):** 180
**Availability:** 6:00-22:00
**Booking required:** True
**Minimum notice (hours):** 4
**Description:** Entrust your little ones to our Kids Club Session, a 180-minute program that promotes social interaction. Our certified caregivers use interactive play sessions, ensuring creatively stimulated.

**Name:** Children's Activity Program
**Category:** Childcare Services
**Price (USD):** 120
**Duration (minutes):** 120
**Availability:** 6:00-22:00
**Booking required:** False
**Minimum notice (hours):** 24
**Description:** Give your children an amazing time with our Children's Activity Program, where 120 minutes of age-appropriate activities provides promotes social interaction, guaranteeing happily entertained and enriched.

Is there any other information I can provide about the hotel?

In [53]:
result = amenities_agent.invoke({"messages": [{"role": "user", "content": "What can I do at the pool?"}]})
print(get_output_text(result))

16:18:42 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
16:18:42 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
16:18:42 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:18:42 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:18:42 llama_index.vector_stores.redis.base INFO   Querying index amenities with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
16:18:42 llama_index.vector_stores.redis.base INFO   Querying index amenities with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
Querying index amenities with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
16:18:42 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['amenities:AM000014', 'amenities:AM000022', 'amenities:AM000021', 'amenities:AM000011']
16:18:42 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['amenities:AM000014', 'amenities:AM000022', 'amenities:AM000021', 'amenities:AM000011']
Found 4 results for query with id ['amenities:AM000014', 'amenities:AM000022', 'amenities:AM000021', 'amenities:AM000011']
16:18:49 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
16:18:49 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Here’s what I found you can do that’s pool-related:

**Name:** Aqua Fitness Class
**Category:** Fitness Services
**Price (USD):** 45
**Duration (minutes):** 45
**Availability:** 6:00-22:00
**Booking required:** False
**Minimum notice (hours):** 24
**Description:** Transform your fitness journey with our Aqua Fitness Class, a 45-minute session that boosts energy and vitality. Our certified trainers will progressive training methods, ensuring energized and accomplished.

I didn’t find other amenities explicitly described as “at the pool,” but the closest water-activity match I found is:

**Name:** Scuba Diving Experience
**Category:** Luxury Water Sports
**Price (USD):** 400
**Duration (minutes):** 240
**Availability:** By appointment only
**Booking required:** False
**Minimum notice (hours):** 24
**Description:** Embark on an unforgettable Scuba Diving Experience, a 240-minute adventure that provides exclusive water activities. Our experienced team provides personalized attention, ensuring complete satisfaction and adventure.

Is there any other information I can provide about the hotel?

In [54]:
result = amenities_agent.invoke({"messages": [{"role": "user", "content": "What can I do without a booking?"}]})
print(get_output_text(result))

16:18:52 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
16:18:52 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
16:18:53 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:18:53 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:18:53 llama_index.vector_stores.redis.base INFO   Querying index amenities with query @booking_required:{False}=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
16:18:53 llama_index.vector_stores.redis.base INFO   Querying index amenities with query @booking_required:{False}=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
Querying index amenities with query @booking_required:{False}=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
16:18:53 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['amenities:AM000031', 'amenities:AM000014', 'amenities:AM000016', 'amenities:AM000024']
16:18:53 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['amenities:AM000031', 'amenities:AM000014', 'amenities:AM000016', 'amenities:AM000024']
Found 4 results for query with id ['amenities:AM000031', 'amenities:AM000014', 'amenities:AM000016', 'amenities:AM000024']
16:19:00 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
16:19:00 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Here are some amenities I found that do **not** require a booking:

**Name:** Children's Activity Program
**Category:** Childcare Services
**Price (USD):** 120
**Duration (minutes):** 120
**Availability:** 6:00-22:00
**Booking required:** False
**Minimum notice (hours):** 24
**Description:** Give your children an amazing time with our Children's Activity Program, where 120 minutes of age-appropriate activities provides promotes social interaction, guaranteeing happily entertained and enriched.

**Name:** Aqua Fitness Class
**Category:** Fitness Services
**Price (USD):** 45
**Duration (minutes):** 45
**Availability:** 6:00-22:00
**Booking required:** False
**Minimum notice (hours):** 24
**Description:** Transform your fitness journey with our Aqua Fitness Class, a 45-minute session that boosts energy and vitality. Our certified trainers will progressive training methods, ensuring energized and accomplished.

**Name:** Evening Dining
**Category:** Room Service
**Price (USD):** 65
**Duration (minutes):** 45
**Availability:** 8:00-20:00
**Booking required:** False
**Minimum notice (hours):** 0
**Description:** Indulge in the convenience of our Evening Dining, where 45 minutes of professional service presentation brings satisfies your gourmet cravings, providing perfect satisfaction.

**Name:** Live Music Performance
**Category:** Entertainment Services
**Price (USD):** 800
**Duration (minutes):** 120
**Availability:** 24/7
**Booking required:** False
**Minimum notice (hours):** 2
**Description:** Let us enchant you with our Live Music Performance, where 120 minutes of customized show programming creates delivers premium entertainment, delivering immersed in pure entertainment.

Is there any other information I can provide about the hotel?

In [55]:
result = amenities_agent.invoke({"messages": [{"role": "user", "content": "What can I see at your petting zoo?"}]})
print(get_output_text(result))

16:19:02 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
16:19:02 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
16:19:03 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:19:03 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:19:03 llama_index.vector_stores.redis.base INFO   Querying index amenities with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
16:19:03 llama_index.vector_stores.redis.base INFO   Querying index amenities with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
Querying index amenities with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
16:19:03 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['amenities:AM000030', 'amenities:AM000031', 'amenities:AM000029', 'amenities:AM000023']
16:19:03 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['amenities:AM000030', 'amenities:AM000031', 'amenities:AM000029', 'amenities:AM000023']
Found 4 results for query with id ['amenities:AM000030', 'amenities:AM000031', 'amenities:AM000029', 'amenities:AM000023']
16:19:09 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
16:19:09 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
I looked up “petting zoo,” but I couldn’t find any amenity listing that describes a petting zoo or what animals you can see; here are the closest child-focused activities I found:

**Name:** Children's Activity Program
**Category:** Childcare Services
**Price (USD):** 120
**Duration (minutes):** 120
**Availability:** 6:00-22:00
**Booking required:** False
**Minimum notice (hours):** 24
**Description:** Give your children an amazing time with our Children's Activity Program, where 120 minutes of age-appropriate activities provides promotes social interaction, guaranteeing happily entertained and enriched.

**Name:** Kids Club Session
**Category:** Childcare Services
**Price (USD):** 80
**Duration (minutes):** 180
**Availability:** 6:00-22:00
**Booking required:** True
**Minimum notice (hours):** 4
**Description:** Entrust your little ones to our Kids Club Session, a 180-minute program that promotes social interaction. Our certified caregivers use interactive play sessions, ensuring creatively stimulated.

**Name:** Private Babysitting
**Category:** Childcare Services
**Price (USD):** 100
**Duration (minutes):** 240
**Availability:** 6:00-22:00
**Booking required:** False
**Minimum notice (hours):** 0
**Description:** Give your children an amazing time with our Private Babysitting, where 240 minutes of interactive play sessions provides promotes social interaction, guaranteeing socially connected and happy.

Is there any other information I can provide about the hotel?

### Services

I would like to combine this with amenities as the dataset columns are almost identical, but this set doesn't have availability information. In practice, I would just ask for this information, but I can't do that here, so I'm keeping them separate.

Connect to Redis Cloud

In [56]:
from llama_index.core import StorageContext, VectorStoreIndex
from llama_index.vector_stores.redis import RedisVectorStore
from redisvl.schema import IndexSchema

redis_conn_string = os.getenv("REDIS_URL")
services_schema = IndexSchema.from_dict(
    {
        "index": {"name": "services", "prefix": "services"},
        # customize fields that are indexed
        "fields": [
            # required fields for llamaindex
            {"type": "tag", "name": "id"},
            {"type": "tag", "name": "doc_id"},
            {"type": "text", "name": "text"},
            # custom fields for filtering
            {"type": "tag", "name": "service_type"},
            {"type": "numeric", "name": "price"},
            {"type": "numeric", "name": "duration"},
            {"type": "numeric", "name": "min_notice_hours"},
            {"type": "tag", "name": "department"},
            {"type": "tag", "name": "booking_required"},
            # custom vector field for text-embedding-3-small embeddings
            {
                "type": "vector",
                "name": "vector",
                "attrs": {
                    "dims": 1536,
                    "algorithm": "hnsw",
                    "distance_metric": "cosine",
                },
            },
        ],
    },
)
redis_client = Redis.from_url(redis_conn_string, decode_responses=True)
services_vector_store = RedisVectorStore(schema=services_schema, redis_client=redis_client, overwrite=True)
services_storage_context = StorageContext.from_defaults(vector_store=services_vector_store)

16:19:09 redisvl.index.index INFO   Index already exists, overwriting.
16:19:09 redisvl.index.index INFO   Index already exists, overwriting.
Index already exists, overwriting.

Add services information

In [57]:
df_services = pd.read_pickle("../data/pandas/services.pkl")
df_services

,service_type,name,description,duration_minutes,price,department,booking_required,min_notice_hours
service_id,,,,,,,,
SV000001,Spa Treatment,Spa Treatment - 120 min,Swedish massage for 120 minutes using Modern t...,120,264.98,Spa & Wellness,True,4
SV000002,Spa Treatment,Spa Treatment - 60 min,Luxurious 60-minute Deep Tissue treatment feat...,60,232.03,Spa & Wellness,True,4
SV000003,Spa Treatment,Spa Treatment - 120 min,Premium Deep Tissue experience for 120 minutes...,120,251.99,Spa & Wellness,True,24
SV000004,Spa Treatment,Spa Treatment - 90 min,Luxurious 90-minute Hot Stone treatment featur...,90,157.55,Spa & Wellness,True,1
SV000005,Personal Training,Personal Training - 60 min,Custom 60-minute HIIT workout emphasizing Core...,60,133.13,Fitness Center,True,4
SV000006,Personal Training,Personal Training - 30 min,Personalized HIIT training for 30 minutes targ...,30,138.75,Fitness Center,True,4
SV000007,Personal Training,Personal Training - 60 min,Personalized Functional Fitness training for 6...,60,82.20,Fitness Center,True,24
SV000008,Personal Training,Personal Training - 60 min,Custom 60-minute Strength Training workout emp...,60,143.70,Fitness Center,True,2
SV000009,Wellness Consultation,Wellness Consultation - 60 min,In-depth Wellness Strategy session for 60 minu...,60,94.86,Spa & Wellness,True,1
SV000010,Wellness Consultation,Wellness Consultation - 45 min,Comprehensive 45-minute Nutrition Planning ass...,45,109.60,Spa & Wellness,True,2
SV000011,Wellness Consultation,Wellness Consultation - 60 min,Comprehensive 60-minute Lifestyle Assessment a...,60,130.29,Spa & Wellness,True,4
SV000012,Wellness Consultation,Wellness Consultation - 45 min,In-depth Wellness Strategy session for 45 minu...,45,118.17,Spa & Wellness,True,1
SV000013,Massage Therapy,Massage Therapy - 30 min,30-minute Recovery massage using Trigger Point...,30,91.32,Spa & Wellness,True,24
SV000014,Massage Therapy,Massage Therapy - 90 min,Specialized Sports Massage therapy session for...,90,157.61,Spa & Wellness,True,24
SV000015,Massage Therapy,Massage Therapy - 60 min,Specialized Recovery therapy session for 60 mi...,60,159.75,Spa & Wellness,True,4
SV000016,Massage Therapy,Massage Therapy - 90 min,Targeted 90-minute Recovery treatment employin...,90,117.71,Spa & Wellness,True,1
SV000017,Fitness Assessment,Fitness Assessment - 60 min,Professional 60-minute Movement Screening anal...,60,116.08,Fitness Center,True,24
SV000018,Fitness Assessment,Fitness Assessment - 60 min,Professional 60-minute Comprehensive Fitness T...,60,88.23,Fitness Center,True,2
SV000019,Fitness Assessment,Fitness Assessment - 60 min,Detailed Movement Screening assessment for 60 ...,60,74.60,Fitness Center,True,24
SV000020,Fitness Assessment,Fitness Assessment - 60 min,Professional 60-minute Performance Evaluation ...,60,60.63,Fitness Center,True,4
SV000021,Group Fitness Class,Group Fitness Class - 45 min,Dynamic HIIT session for 45 minutes targeting ...,45,48.11,Fitness Center,True,24
SV000022,Group Fitness Class,Group Fitness Class - 60 min,Energetic 60-minute HIIT class focusing on Str...,60,43.88,Fitness Center,True,2
SV000023,Group Fitness Class,Group Fitness Class - 60 min,Energetic 60-minute Boot Camp class focusing o...,60,25.21,Fitness Center,True,4
SV000024,Group Fitness Class,Group Fitness Class - 45 min,Engaging 45-minute Pilates class emphasizing S...,45,30.93,Fitness Center,True,1
SV000025,Group Fitness Class,Group Fitness Class - 45 min,Engaging 45-minute Yoga class emphasizing Full...,45,40.18,Fitness Center,True,2

In [58]:
def get_services_nodes():
    nodes = []
    for id_, row in df_services.iterrows():
        main_text = "Name:" + row["name"] + "\n\nDescription:\n" + row["description"]
        metadata = {"service_type": row["service_type"],
                    "duration": row["duration_minutes"],
                    "price": row["price"],
                    "department": row["department"],
                    "booking_required": str(row["booking_required"]),
                    "min_notice_hours": row["min_notice_hours"]}
        node = TextNode(text=main_text, id_=id_, metadata=metadata)
        nodes.append(node)
    return nodes

services_nodes = get_services_nodes()

In [59]:
services_index = VectorStoreIndex(nodes=services_nodes, storage_context=services_storage_context)
services_retriever = services_index.as_retriever(similarity_top_k=top_k)

16:19:10 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:19:10 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:19:10 llama_index.vector_stores.redis.base INFO   Added 25 documents to index services
16:19:10 llama_index.vector_stores.redis.base INFO   Added 25 documents to index services
Added 25 documents to index services

In [60]:
services_retriever.retrieve("I want to do some pilates.")

16:19:11 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:19:11 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:19:11 llama_index.vector_stores.redis.base INFO   Querying index services with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
16:19:11 llama_index.vector_stores.redis.base INFO   Querying index services with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
Querying index services with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
16:19:11 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['services:SV000024', 'services:SV000025', 'services:SV000005', 'services:SV000008']
16:19:11 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['services:SV000024', 'services:SV000025', 'services:SV000005', 'services:SV000008']
Found 4 results for query with id ['services:SV000024', 'services:SV000025', 'services:SV000005', 'services:SV000008']

[NodeWithScore(node=TextNode(id_='SV000024', embedding=None, metadata={'service_type': 'Group Fitness Class', 'duration': 45, 'price': 30.93, 'department': 'Fitness Center', 'booking_required': 'True', 'min_notice_hours': 1}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Name:Group Fitness Class - 45 min\n\nDescription:\nEngaging 45-minute Pilates class emphasizing Strength. Group Motivation.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.491133868694),
 NodeWithScore(node=TextNode(id_='SV000025', embedding=None, metadata={'service_type': 'Group Fitness Class', 'duration': 45, 'price': 40.18, 'department': 'Fitness Center', 'booking_required': 'True', 'min_notice_hours': 2}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Name:Group Fitness Class - 45 min\n\nDescription:\nEngaging 45-minute Yoga class emphasizing Full Body Workout. Expert Guidance.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.384283065796),
 NodeWithScore(node=TextNode(id_='SV000005', embedding=None, metadata={'service_type': 'Personal Training', 'duration': 60, 'price': 133.13, 'department': 'Fitness Center', 'booking_required': 'True', 'min_notice_hours': 4}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Name:Personal Training - 60 min\n\nDescription:\nCustom 60-minute HIIT workout emphasizing Core. Weight Management.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.37706768512699995),
 NodeWithScore(node=TextNode(id_='SV000008', embedding=None, metadata={'service_type': 'Personal Training', 'duration': 60, 'price': 143.7, 'department': 'Fitness Center', 'booking_required': 'True', 'min_notice_hours': 2}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Name:Personal Training - 60 min\n\nDescription:\nCustom 60-minute Strength Training workout emphasizing Full Body. Better Flexibility.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.35639154911000004)]

Setup the retriever and filter over metadata (manually again). Uses the _range_filters from above.

In [61]:
from langchain.tools import tool
from llama_index.core.retrievers import VectorIndexRetriever


@tool(parse_docstring=True)
def query_services(  # noqa: PLR0913
    query: str,
    booking_required: bool | None = None,  # noqa: FBT001
    min_price: float | None = None,
    max_price: float | None = None,
    min_notice_hours: int | None = None,
    max_notice_hours: int | None = None,
    min_duration_minutes: int | None = None,
    max_duration_minutes: int | None = None,
) -> list[RetrievalItem]:
    """Provide information about the hotel's services in response to a passed-in query.

    Supports optional range filtering on numeric fields.

    Args:
        query (string): The query string.
        booking_required: Restrict results to booking_required==True/False.
        min_price (float, optional): Minimum price (inclusive).
        max_price (float, optional): Maximum price (inclusive).
        min_notice_hours (int, optional): Minimum notice hours (inclusive).
        max_notice_hours (int, optional): Maximum notice hours (inclusive).
        min_duration_minutes (int, optional): Minimum duration in minutes (inclusive).
        max_duration_minutes (int, optional): Maximum duration in minutes (inclusive).

    Returns:
        list[RetrievalItem]: The retrieved results and their associated source,
        metadata, and RAG similarity score.

    """
    filters = _range_filters(
        booking_required=booking_required,
        min_price=min_price,
        max_price=max_price,
        min_notice_hours=min_notice_hours,
        max_notice_hours=max_notice_hours,
        min_duration_minutes=min_duration_minutes,
        max_duration_minutes=max_duration_minutes,
    )

    retriever = VectorIndexRetriever(index=services_index, filters=filters, similarity_top_k=top_k)

    nodes = retriever.retrieve(query)

    return [RetrievalItem(source = "services",
                          metadata = dict(getattr(n, "metadata", {})),
                          text = getattr(n, "text", ""),
                          score =  getattr(n, "score", 0))
            for n in nodes]

In [62]:
from langchain.agents import create_agent
from langchain_openai import ChatOpenAI

SYSTEM_PROMPT = """You are a hotel information assistant. You must answer user questions only using information returned by the hotel services search tool.

**Core rules**
* Always use the tool to look up amenities relevant to the user's request before answering.
* Do not invent, guess, or infer details that are not explicitly present in tool results.
* If the user asks for something not found, say you couldn't find it and offer the closest relevant matches (if any).
* Your results are not exhaustive; do not claim completeness.
* Assume all prices are in USD unless the tool indicates otherwise.
* Do not mention "database," "RAG," "embeddings," or internal implementation. You may say you "looked it up" or "searched."

**Retrieval behavior**
* Convert the user's request into a search intent (service types, keywords, constraints like price/duration/availability).
* Prefer precision: return only services that clearly match the request.
* If the request is broad ("spa options"), return a small curated set (e.g., 3-8) that best represent the service type.
* If the request is narrow and no exact hit exists, return near matches and explain why they're the closest.

**Response requirements**
You may provide a once sentence introduction to the results. List the relevant services afterwards.
For each service you include, present **only** the fields you have from the tool, using this schema and order:

**Name:**
**Service type:**
**Department:**
**Price (USD):**
**Duration (minutes):**
**Booking required:**
**Minimum notice (hours):**
**Description:**

* If a field is missing from the tool output, write "Not specified."
* Do not add advice, policies, instructions, or booking steps unless the tool output explicitly contains them.
* Do not offer to perform actions (booking, calling, emailing, etc.).

**After answering**
End with exactly one question:
"Is there any other information I can provide about the hotel?"
"""

gpt_version="gpt-5.2"
services_llm = ChatOpenAI(model=gpt_version, temperature=0, reasoning={"effort": "medium"})
services_agent = create_agent(model=services_llm, tools=[query_services], system_prompt=SYSTEM_PROMPT)

In [63]:
def get_output_text(query_result) -> str:
    last_result = query_result["messages"][-1]
    for c in last_result.content:
        if "text" in c:
            return c["text"]
    return ""

In [64]:
result = services_agent.invoke({"messages": [{"role": "user", "content": "I would like an hour long massage"}]})
print(get_output_text(result))

16:19:13 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
16:19:13 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
16:19:13 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:19:13 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:19:13 llama_index.vector_stores.redis.base INFO   Querying index services with query (@duration:[60 +inf] @duration:[-inf 60])=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
16:19:13 llama_index.vector_stores.redis.base INFO   Querying index services with query (@duration:[60 +inf] @duration:[-inf 60])=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
Querying index services with query (@duration:[60 +inf] @duration:[-inf 60])=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
16:19:13 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['services:SV000015', 'services:SV000002', 'services:SV000017', 'services:SV000011']
16:19:13 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['services:SV000015', 'services:SV000002', 'services:SV000017', 'services:SV000011']
Found 4 results for query with id ['services:SV000015', 'services:SV000002', 'services:SV000017', 'services:SV000011']
16:19:19 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
16:19:19 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
**Name:** Massage Therapy - 60 min
**Service type:** Massage Therapy
**Department:** Spa & Wellness
**Price (USD):** 159.75
**Duration (minutes):** 60
**Booking required:** True
**Minimum notice (hours):** 4
**Description:** Specialized Recovery therapy session for 60 minutes with Deep Tissue approach. Improved Mobility.

Is there any other information I can provide about the hotel?

In [65]:
result = services_agent.invoke({"messages": [{"role": "user", "content": "What can I do for between $50 and $100?"}]})
print(get_output_text(result))

16:19:22 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
16:19:22 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
16:19:22 llama_index.vector_stores.redis.base INFO   Querying index services with query (@price:[50.0 +inf] @price:[-inf 100.0]) RETURN 4 id doc_id text _node_content DIALECT 2 LIMIT 0 4
16:19:22 llama_index.vector_stores.redis.base INFO   Querying index services with query (@price:[50.0 +inf] @price:[-inf 100.0]) RETURN 4 id doc_id text _node_content DIALECT 2 LIMIT 0 4
Querying index services with query (@price:[50.0 +inf] @price:[-inf 100.0]) RETURN 4 id doc_id text _node_content DIALECT 2 LIMIT 0 4
16:19:23 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['services:SV000007', 'services:SV000009', 'services:SV000013', 'services:SV000018']
16:19:23 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['services:SV000007', 'services:SV000009', 'services:SV000013', 'services:SV000018']
Found 4 results for query with id ['services:SV000007', 'services:SV000009', 'services:SV000013', 'services:SV000018']
16:19:27 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
16:19:27 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
16:19:28 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:19:28 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:19:28 llama_index.vector_stores.redis.base INFO   Querying index services with query (@price:[50.0 +inf] @price:[-inf 100.0])=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
16:19:28 llama_index.vector_stores.redis.base INFO   Querying index services with query (@price:[50.0 +inf] @price:[-inf 100.0])=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
Querying index services with query (@price:[50.0 +inf] @price:[-inf 100.0])=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
16:19:28 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['services:SV000009', 'services:SV000019', 'services:SV000007', 'services:SV000020']
16:19:28 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['services:SV000009', 'services:SV000019', 'services:SV000007', 'services:SV000020']
Found 4 results for query with id ['services:SV000009', 'services:SV000019', 'services:SV000007', 'services:SV000020']
16:19:33 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
16:19:33 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Here are some hotel services I found priced between **$50 and $100**:

**Name:** Wellness Consultation - 60 min
**Service type:** Wellness Consultation
**Department:** Spa & Wellness
**Price (USD):** 94.86
**Duration (minutes):** 60
**Booking required:** True
**Minimum notice (hours):** 1
**Description:** In-depth Wellness Strategy session for 60 minutes addressing Sleep Improvement. Personalized Plan.

**Name:** Fitness Assessment - 60 min
**Service type:** Fitness Assessment
**Department:** Fitness Center
**Price (USD):** 74.6
**Duration (minutes):** 60
**Booking required:** True
**Minimum notice (hours):** 24
**Description:** Detailed Movement Screening assessment for 60 minutes examining Cardio Capacity. Program Optimization.

**Name:** Personal Training - 60 min
**Service type:** Personal Training
**Department:** Fitness Center
**Price (USD):** 82.2
**Duration (minutes):** 60
**Booking required:** True
**Minimum notice (hours):** 24
**Description:** Personalized Functional Fitness training for 60 minutes targeting Lower Body. Enhanced Endurance.

**Name:** Fitness Assessment - 60 min
**Service type:** Fitness Assessment
**Department:** Fitness Center
**Price (USD):** 60.63
**Duration (minutes):** 60
**Booking required:** True
**Minimum notice (hours):** 4
**Description:** Professional 60-minute Performance Evaluation analyzing Overall Fitness. Program Optimization.

Is there any other information I can provide about the hotel?

### Combine into a single agent

For reranking. Passing along everything to the reranker and expecting the LLM to copy it all does not work well.

In [88]:
class RetrievalItemLite(BaseModel):
    source: str = Field(..., description="FAQ | amenities | services")
    item_id: str = Field(..., description="Stable identifier for this item")
    score: float = Field(..., description="Similarity score; higher is more relevant")

Re-define (or define for the first time for FAQ) query tools to return RetrievalItemLite

In [89]:
from langchain.tools import tool


@tool(parse_docstring=True)
def query_faq(query: str) -> list[RetrievalItemLite]:
    """Retrieve FAQ entries relevant to a user query.

    This tool performs vector search over the **FAQ** knowledge base. Use it
    when the user asks about hotel policies, rules, hours, check-in/check-out,
    deposits, cancellations, parking, pet policy, accessibility, or other
    "how does the hotel work" questions.

    Notes:
        - This tool returns lightweight items (source, item_id, score). The
            system will later rerank across sources and then hydrate the final
            selection to retrieve full text + metadata.
        - If you are unsure whether a question is policy-related, it is still
            safe to call this tool; irrelevant FAQ hits will be dropped later.

    Args:
        query: Natural-language query describing what the user wants.

    Returns:
        list[RetrievalItemLite]: Up to ``top_k`` lightweight FAQ matches.

    Examples:
        - "What time is check-in?"
        - "Do you allow pets?"
        - "Is there parking and how much does it cost?"
        - "What is the cancellation policy?"

    """
    nodes = faq_retriever.retrieve(query)

    return [RetrievalItemLite(source = "faq",
                          item_id = getattr(n, "id_", ""),
                          score =  getattr(n, "score", 0))
            for n in nodes]

In [90]:
@tool(parse_docstring=True)
def query_amenities(
    query: str,
    booking_required: bool | None = None,  # noqa: FBT001
    min_price: float | None = None,
    max_price: float | None = None,
    min_notice_hours: int | None = None,
    max_notice_hours: int | None = None,
    min_duration_minutes: int | None = None,
    max_duration_minutes: int | None = None,
) -> list[RetrievalItemLite]:
    """Retrieve hotel amenities relevant to a user query.

    This tool performs vector search over the **amenities** catalog and can
    apply optional metadata constraints. All provided constraints are combined
    using logical **AND**.

    Use this tool when the user asks about amenities such as facilities,
    on-property features, classes, rentals, or other amenity offerings.

    Args:
        query: Natural-language query describing what the user wants.
        booking_required: Restrict results to booking_required==True/False.
        min_price: Minimum price in USD (inclusive).
        max_price: Maximum price in USD (inclusive).
        min_notice_hours: Minimum advance notice in hours (inclusive).
        max_notice_hours: Maximum advance notice in hours (inclusive).
        min_duration_minutes: Minimum duration in minutes (inclusive).
        max_duration_minutes: Maximum duration in minutes (inclusive).

    Returns:
        list[RetrievalItemLite]: Up to ``top_k`` lightweight results.

    """
    filters = _range_filters(
        booking_required=booking_required,
        min_price=min_price,
        max_price=max_price,
        min_notice_hours=min_notice_hours,
        max_notice_hours=max_notice_hours,
        min_duration_minutes=min_duration_minutes,
        max_duration_minutes=max_duration_minutes,
    )

    retriever = VectorIndexRetriever(
        index=amenities_index, extra_filters=filters,
        similarity_top_k=top_k)

    nodes = retriever.retrieve(query)

    return [RetrievalItemLite(source = "amenities",
                          item_id = getattr(n, "id_", ""),
                          score =  getattr(n, "score", 0))
            for n in nodes]

In [91]:
@tool(parse_docstring=True)
def query_services(
    query: str,
    booking_required: bool | None = None,  # noqa: FBT001
    min_price: float | None = None,
    max_price: float | None = None,
    min_notice_hours: int | None = None,
    max_notice_hours: int | None = None,
    min_duration_minutes: int | None = None,
    max_duration_minutes: int | None = None,
) -> list[RetrievalItemLite]:
    """Retrieve hotel services relevant to a user query.

    This tool performs vector search over the **services** catalog (e.g.,
    spa treatments, housekeeping add-ons, transportation, concierge offerings,
    dining-related services, etc.).

    You may optionally apply metadata constraints. All provided constraints are
    combined using logical **AND**.

    Use this tool when the user asks for *staff-provided* or *bookable* services
    rather than physical amenities.

    Args:
        query: Natural-language query describing what the user wants.
        booking_required: Restrict results to booking_required==True/False.
        min_price: Minimum price in USD (inclusive).
        max_price: Maximum price in USD (inclusive).
        min_notice_hours: Minimum advance notice in hours (inclusive).
        max_notice_hours: Maximum advance notice in hours (inclusive).
        min_duration_minutes: Minimum duration in minutes (inclusive).
        max_duration_minutes: Maximum duration in minutes (inclusive).

    Returns:
        list[RetrievalItemLite]: Up to ``top_k`` lightweight results.

    Examples:
        - "airport shuttle"
        - "in-room massage under $200"
        - "late checkout service"
        - "laundry with at least 2 hours notice"

    """
    filters = _range_filters(
        booking_required=booking_required,
        min_price=min_price,
        max_price=max_price,
        min_notice_hours=min_notice_hours,
        max_notice_hours=max_notice_hours,
        min_duration_minutes=min_duration_minutes,
        max_duration_minutes=max_duration_minutes,
    )

    retriever = VectorIndexRetriever(index=services_index, filters=filters, similarity_top_k=top_k)

    nodes = retriever.retrieve(query)

    return [RetrievalItemLite(source = "services",
                          item_id = getattr(n, "id_", ""),
                          score =  getattr(n, "score", 0))
            for n in nodes]

Reranker tool for returning combined top k results

In [ ]:
import heapq

class RerankInput(BaseModel):
    faq_results: list[RetrievalItemLite] = Field(..., description="Output from query_faq")
    amenities_results: list[RetrievalItemLite] = Field(..., description="Output from query_amenities")
    services_results: list[RetrievalItemLite] = Field(..., description="Output from query_services")

@tool(args_schema=RerankInput)
def reranker(
    faq_results: list[RetrievalItemLite],
    amenities_results: list[RetrievalItemLite],
    services_results: list[RetrievalItemLite],
    ) -> list[RetrievalItemLite]:
    """Select the top-k results across FAQ, amenities, and services.

    This tool merges results from earlier retrieval tools and selects the
    highest-scoring items.

    Args:
        faq_results: Output from ``query_faq``.
        amenities_results: Output from ``query_amenities``.
        services_results: Output from ``query_services``.

    Returns:
        list[RetrievalItemLite]: The top-k items by score.

    """
    all_results = faq_results + amenities_results + services_results
    return heapq.nlargest(top_k, all_results, key=lambda x: x.score)

Retrieve the data that the LLM needs to put together a response

In [93]:
import json


class HydrateInput(BaseModel):
    items: list[RetrievalItemLite] = Field(..., description="Top items from reranker")

@tool(args_schema=HydrateInput)
def hydrate_items(items: list[RetrievalItemLite]) -> list[RetrievalItem]:
    """Hydrate reranked items into full text + metadata objects.

    Args:
        items: Lightweight items returned by the reranker.

    Returns:
        list[RetrievalItem]: Hydrated results. Returns an empty list on
        operational failures.

    """
    out: list[RetrievalItem] = []
    for it in items:
        prefix = it.source.lower()
        data_list = redis_client.hmget(f"{prefix}:{it.item_id}",
                                       ["_node_content", "text"])

        # Fallback: if you can't docstore-get by node_id, you need a deterministic fetch strategy.
        # One common fallback is to store a stable 'doc_id' in metadata and filter retrieval by it.
        if data_list is None:
            error_str = f"Could not hydrate item_id={it.item_id} from source={it.source}."
            raise RuntimeError(error_str)

        data = json.loads(data_list[0])
        text = data_list[1]

        out.append(
            RetrievalItem(
                source=it.source,
                metadata=data["metadata"],
                text=text or "",
                score=it.score,
            ),
        )
    return out

Setup and prompt the LLM

In [97]:
from pathlib import Path
from string import Template

from langchain.agents import create_agent
from langchain_openai import ChatOpenAI

info_prompt_path = Path("../blue_horizon/system_prompts/information.txt")
info_prompt_template = Template(info_prompt_path.read_text(encoding="utf-8"))
info_system_prompt = info_prompt_template.safe_substitute(top_k=top_k)

gpt_version="gpt-5.2"
info_llm = ChatOpenAI(model=gpt_version, temperature=0, reasoning={"effort": "medium"})
combined_agent = create_agent(
    model=info_llm,
    tools=[query_faq, query_amenities, query_services, reranker, hydrate_items],
    system_prompt=info_system_prompt,
    )

In [98]:
from langchain_core.messages import HumanMessage
result = combined_agent.invoke({"messages": [HumanMessage(content="I want an hour long massage.")]})
print(get_output_text(result))

16:40:56 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
16:40:56 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
16:40:56 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:40:56 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:40:56 llama_index.vector_stores.redis.base INFO   Querying index services with query (@duration:[60 +inf] @duration:[-inf 60])=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
16:40:56 llama_index.vector_stores.redis.base INFO   Querying index services with query (@duration:[60 +inf] @duration:[-inf 60])=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
Querying index services with query (@duration:[60 +inf] @duration:[-inf 60])=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
16:40:56 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['services:SV000015', 'services:SV000002', 'services:SV000017', 'services:SV000008']
16:40:56 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['services:SV000015', 'services:SV000002', 'services:SV000017', 'services:SV000008']
Found 4 results for query with id ['services:SV000015', 'services:SV000002', 'services:SV000017', 'services:SV000008']
16:40:56 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:40:56 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:40:56 llama_index.vector_stores.redis.base INFO   Querying index amenities with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
16:40:56 llama_index.vector_stores.redis.base INFO   Querying index amenities with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
Querying index amenities with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
16:40:56 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['amenities:AM000002', 'amenities:AM000001', 'amenities:AM000003', 'amenities:AM000004']
16:40:56 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['amenities:AM000002', 'amenities:AM000001', 'amenities:AM000003', 'amenities:AM000004']
Found 4 results for query with id ['amenities:AM000002', 'amenities:AM000001', 'amenities:AM000003', 'amenities:AM000004']
16:41:06 httpx INFO   HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
16:41:06 httpx INFO   HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
16:41:06 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using query str: hour long massage 60 minute massage
16:41:06 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using query str: hour long massage 60 minute massage
Using query str: hour long massage 60 minute massage
16:41:06 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using filters: []
16:41:06 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using filters: []
Using filters: []
16:41:06 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using top_k: 4
16:41:06 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using top_k: 4
Using top_k: 4
16:41:06 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:41:06 httpx INFO   HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
16:41:06 llama_index.vector_stores.redis.base INFO   Querying index faq with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
16:41:06 llama_index.vector_stores.redis.base INFO   Querying index faq with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
Querying index faq with query *=>[KNN 4 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 4
16:41:06 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['faq:FAQ000010', 'faq:FAQ000005', 'faq:FAQ000002', 'faq:FAQ000011']
16:41:06 llama_index.vector_stores.redis.base INFO   Found 4 results for query with id ['faq:FAQ000010', 'faq:FAQ000005', 'faq:FAQ000002', 'faq:FAQ000011']
Found 4 results for query with id ['faq:FAQ000010', 'faq:FAQ000005', 'faq:FAQ000002', 'faq:FAQ000011']
16:41:09 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
16:41:09 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
16:41:11 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
16:41:11 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
16:41:19 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
16:41:19 httpx INFO   HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Here are the hour-long (60-minute) massage options I found:

**Massage Therapy - 60 min**
  **Service type:** Massage Therapy
  **Department:** Spa & Wellness
  **Price (USD):** 159.75
  **Duration (minutes):** 60
  **Booking required:** True
  **Minimum notice (hours):** 4
  **Description:** Specialized Recovery therapy session for 60 minutes with Deep Tissue approach. Improved Mobility.

**Spa Treatment - 60 min**
  **Service type:** Spa Treatment
  **Department:** Spa & Wellness
  **Price (USD):** 232.03
  **Duration (minutes):** 60
  **Booking required:** True
  **Minimum notice (hours):** 4
  **Description:** Luxurious 60-minute Deep Tissue treatment featuring Herbal Products and Traditional methods. Improved Circulation.

**Deep Tissue Massage**
  **Category:** Spa Services
  **Price (USD):** 140
  **Duration (minutes):** 60
  **Availability:** 6:00-22:00
  **Booking required:** False
  **Minimum notice (hours):** 4
  **Description:** Indulge in our signature Deep Tissue Massage, where 60 minutes of expert care will melt away stress and tension. This treatment features natural skincare products and customized therapeutic approaches to provide rejuvenated and restored.

**Swedish Massage**
  **Category:** Spa Services
  **Price (USD):** 120
  **Duration (minutes):** 60
  **Availability:** 24/7
  **Booking required:** True
  **Minimum notice (hours):** 2
  **Description:** Experience pure relaxation with our Swedish Massage, a 60-minute treatment designed to melt away stress and tension. Our certified therapists use premium natural skincare products to precise pressure point therapy, leaving you feeling renewed and revitalized.

Is there any other information I can provide about the hotel? I can also help finding and booking a room.