Setup a Redis vector store that works with LlamaIndex for the FAQ, amenities, and services info.

I provide metadata information because LlamaIndex can have the LLM filter by it.

Load environment variables from .env file

In [1]:
import os

from dotenv import load_dotenv

load_dotenv("../.env")

True

For info on what's happening in the background

In [2]:
import logging
import sys

logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))

Setup the embedding model

In [3]:
from llama_index.core import Settings
from llama_index.embeddings.huggingface import HuggingFaceEmbedding

In [4]:
Settings.embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")

INFO:sentence_transformers.SentenceTransformer:Load pretrained SentenceTransformer: BAAI/bge-small-en-v1.5
Load pretrained SentenceTransformer: BAAI/bge-small-en-v1.5
DEBUG:httpcore.connection:connect_tcp.started host='huggingface.co' port=443 local_address=None timeout=10 socket_options=None
connect_tcp.started host='huggingface.co' port=443 local_address=None timeout=10 socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x000001DA2141CEC0>
connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x000001DA2141CEC0>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x000001DA2113F570> server_hostname='huggingface.co' timeout=10
start_tls.started ssl_context=<ssl.SSLContext object at 0x000001DA2113F570> server_hostname='huggingface.co' timeout=10
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x000001DA212F3390>
start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x000001DA212F3390>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'250'), (b'Connection', b'keep-alive'), (b'Date', b'Wed, 24 Dec 2025 20:30:57 GMT'), (b'Location', b'/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2Fmain%2Fmodules.json=&etag=%22952a9b81c0bfd99800fabf352f69c7ccd46c5e43%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-694c4d81-66d53a510d906ae421814893;7437726e-6f94-487d-9dec-03383e5dee2c'), (b'RateLimit', b'"resolvers";r=19999;t=255'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=20000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'5c38ec7c405ec4b44b94cc5a9bb96e735b38267a'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'HIT'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'modules.json; filename="modules.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"952a9b81c0bfd99800fabf352f69c7ccd46c5e43"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 12468094e35c8a577a333f469209441a.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'DEN53-P4'), (b'X-Amz-Cf-Id', b'xi4vP9ixCyzfQZz5EBo6XsdYM0XjHVUgpAYIhNL4g86x4K_oiT5cFA==')])
receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'250'), (b'Connection', b'keep-alive'), (b'Date', b'Wed, 24 Dec 2025 20:30:57 GMT'), (b'Location', b'/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2Fmain%2Fmodules.json=&etag=%22952a9b81c0bfd99800fabf352f69c7ccd46c5e43%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-694c4d81-66d53a510d906ae421814893;7437726e-6f94-487d-9dec-03383e5dee2c'), (b'RateLimit', b'"resolvers";r=19999;t=255'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=20000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'5c38ec7c405ec4b44b94cc5a9bb96e735b38267a'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'HIT'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'modules.json; filename="modules.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"952a9b81c0bfd99800fabf352f69c7ccd46c5e43"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 12468094e35c8a577a333f469209441a.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'DEN53-P4'), (b'X-Amz-Cf-Id', b'xi4vP9ixCyzfQZz5EBo6XsdYM0XjHVUgpAYIhNL4g86x4K_oiT5cFA==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
response_closed.started
DEBUG:httpcore.http11:response_closed.complete
response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'349'), (b'Connection', b'keep-alive'), (b'Date', b'Fri, 28 Nov 2025 03:29:38 GMT'), (b'ETag', b'"952a9b81c0bfd99800fabf352f69c7ccd46c5e43"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-69291722-0d9ccd68586bd7a70f9f535e;80cc8846-d73c-4bd3-84bd-ef817563b2f9'), (b'RateLimit', b'"resolvers";r=19998;t=34'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=20000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'5c38ec7c405ec4b44b94cc5a9bb96e735b38267a'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'modules.json; filename="modules.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 12468094e35c8a577a333f469209441a.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'DEN53-P4'), (b'X-Amz-Cf-Id', b'dF0pWcY3Yq4VIJ-eDqZKdJSSQ3922N4PRSRquoDWEif_xR0VRC2p8w=='), (b'Age', b'2307679')])
receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'349'), (b'Connection', b'keep-alive'), (b'Date', b'Fri, 28 Nov 2025 03:29:38 GMT'), (b'ETag', b'"952a9b81c0bfd99800fabf352f69c7ccd46c5e43"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-69291722-0d9ccd68586bd7a70f9f535e;80cc8846-d73c-4bd3-84bd-ef817563b2f9'), (b'RateLimit', b'"resolvers";r=19998;t=34'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=20000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'5c38ec7c405ec4b44b94cc5a9bb96e735b38267a'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'modules.json; filename="modules.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 12468094e35c8a577a333f469209441a.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'DEN53-P4'), (b'X-Amz-Cf-Id', b'dF0pWcY3Yq4VIJ-eDqZKdJSSQ3922N4PRSRquoDWEif_xR0VRC2p8w=='), (b'Age', b'2307679')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json "HTTP/1.1 200 OK"
HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
response_closed.started
DEBUG:httpcore.http11:response_closed.complete
response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'292'), (b'Connection', b'keep-alive'), (b'Date', b'Wed, 24 Dec 2025 20:30:57 GMT'), (b'Location', b'/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config_sentence_transformers.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2Fmain%2Fconfig_sentence_transformers.json=&etag=%22dcb0c0d97d09b930d13600b1a773ddb27e441aab%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-694c4d81-74fd31b7201225587f21a240;768f9c75-c7e6-4f0d-ba59-b341d31aaf42'), (b'RateLimit', b'"resolvers";r=19998;t=255'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=20000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'5c38ec7c405ec4b44b94cc5a9bb96e735b38267a'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'HIT'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config_sentence_transformers.json; filename="config_sentence_transformers.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"dcb0c0d97d09b930d13600b1a773ddb27e441aab"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 12468094e35c8a577a333f469209441a.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'DEN53-P4'), (b'X-Amz-Cf-Id', b'rV9u--qXp_HGCk5s3Ehtw4QmBS7vBsN1zrL0WsW0kPTgz6mioPFrZA==')])
receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'292'), (b'Connection', b'keep-alive'), (b'Date', b'Wed, 24 Dec 2025 20:30:57 GMT'), (b'Location', b'/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config_sentence_transformers.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2Fmain%2Fconfig_sentence_transformers.json=&etag=%22dcb0c0d97d09b930d13600b1a773ddb27e441aab%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-694c4d81-74fd31b7201225587f21a240;768f9c75-c7e6-4f0d-ba59-b341d31aaf42'), (b'RateLimit', b'"resolvers";r=19998;t=255'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=20000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'5c38ec7c405ec4b44b94cc5a9bb96e735b38267a'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'HIT'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config_sentence_transformers.json; filename="config_sentence_transformers.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"dcb0c0d97d09b930d13600b1a773ddb27e441aab"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 12468094e35c8a577a333f469209441a.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'DEN53-P4'), (b'X-Amz-Cf-Id', b'rV9u--qXp_HGCk5s3Ehtw4QmBS7vBsN1zrL0WsW0kPTgz6mioPFrZA==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
response_closed.started
DEBUG:httpcore.http11:response_closed.complete
response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'124'), (b'Connection', b'keep-alive'), (b'Date', b'Fri, 28 Nov 2025 03:29:39 GMT'), (b'ETag', b'"dcb0c0d97d09b930d13600b1a773ddb27e441aab"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-69291723-24ea6f320770dd602d6a4ef1;9813c62a-113f-4c52-a542-9100563a5f70'), (b'RateLimit', b'"resolvers";r=19995;t=33'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=20000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'5c38ec7c405ec4b44b94cc5a9bb96e735b38267a'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config_sentence_transformers.json; filename="config_sentence_transformers.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 12468094e35c8a577a333f469209441a.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'DEN53-P4'), (b'X-Amz-Cf-Id', b'juaE0s_7k86qefyqj17pv1bftsbmNnERxmRi5sGG_E1Hnx4pFskznA=='), (b'Age', b'2307678')])
receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'124'), (b'Connection', b'keep-alive'), (b'Date', b'Fri, 28 Nov 2025 03:29:39 GMT'), (b'ETag', b'"dcb0c0d97d09b930d13600b1a773ddb27e441aab"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-69291723-24ea6f320770dd602d6a4ef1;9813c62a-113f-4c52-a542-9100563a5f70'), (b'RateLimit', b'"resolvers";r=19995;t=33'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=20000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'5c38ec7c405ec4b44b94cc5a9bb96e735b38267a'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config_sentence_transformers.json; filename="config_sentence_transformers.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 12468094e35c8a577a333f469209441a.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'DEN53-P4'), (b'X-Amz-Cf-Id', b'juaE0s_7k86qefyqj17pv1bftsbmNnERxmRi5sGG_E1Hnx4pFskznA=='), (b'Age', b'2307678')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config_sentence_transformers.json "HTTP/1.1 200 OK"
HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config_sentence_transformers.json "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
response_closed.started
DEBUG:httpcore.http11:response_closed.complete
response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
receive_response_headers.started request=<Request [b'HEAD']>

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: BAAI/bge-small-en-v1.5
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'268'), (b'Connection', b'keep-alive'), (b'Date', b'Wed, 24 Dec 2025 20:30:58 GMT'), (b'Location', b'/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/tokenizer_config.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2Fmain%2Ftokenizer_config.json=&etag=%2237fca74771bc76a8e01178ce3a6055a0995f8093%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-694c4d82-75f2eae76e1f2103731c752b;d069c36f-ef44-48b9-a8cf-f2271158048e'), (b'RateLimit', b'"resolvers";r=19991;t=254'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=20000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'5c38ec7c405ec4b44b94cc5a9bb96e735b38267a'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'HIT'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'tokenizer_config.json; filename="tokenizer_config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"37fca74771bc76a8e01178ce3a6055a0995f8093"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 12468094e35c8a577a333f469209441a.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'DEN53-P4'), (b'X-Amz-Cf-Id', b'JEwArKY44Av4cZBR5EJ1LqtM9tPG75_nRcXK83dBfzQlbcuDGBhZ7g==')])
receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'268'), (b'Connection', b'keep-alive'), (b'Date', b'Wed, 24 Dec 2025 20:30:58 GMT'), (b'Location', b'/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/tokenizer_config.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2Fmain%2Ftokenizer_config.json=&etag=%2237fca74771bc76a8e01178ce3a6055a0995f8093%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-694c4d82-75f2eae76e1f2103731c752b;d069c36f-ef44-48b9-a8cf-f2271158048e'), (b'RateLimit', b'"resolvers";r=19991;t=254'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=20000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'5c38ec7c405ec4b44b94cc5a9bb96e735b38267a'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'HIT'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'tokenizer_config.json; filename="tokenizer_config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"37fca74771bc76a8e01178ce3a6055a0995f8093"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 12468094e35c8a577a333f469209441a.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'DEN53-P4'), (b'X-Amz-Cf-Id', b'JEwArKY44Av4cZBR5EJ1LqtM9tPG75_nRcXK83dBfzQlbcuDGBhZ7g==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
response_closed.started
DEBUG:httpcore.http11:response_closed.complete
response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'366'), (b'Connection', b'keep-alive'), (b'Date', b'Tue, 09 Dec 2025 19:44:49 GMT'), (b'ETag', b'"37fca74771bc76a8e01178ce3a6055a0995f8093"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-69387c31-74d3cfb81844d7c0387d1d34;c4fdfa7c-85bb-4e97-8df8-13c538fca149'), (b'RateLimit', b'"resolvers";r=19988;t=23'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=20000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'5c38ec7c405ec4b44b94cc5a9bb96e735b38267a'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'tokenizer_config.json; filename="tokenizer_config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 12468094e35c8a577a333f469209441a.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'DEN53-P4'), (b'X-Amz-Cf-Id', b'i-JMhLjZH_PwniBX0FH5KHXc-YKEgACfhU-BCU3xHQYJMxIDMAMByw=='), (b'Age', b'1298769')])
receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'366'), (b'Connection', b'keep-alive'), (b'Date', b'Tue, 09 Dec 2025 19:44:49 GMT'), (b'ETag', b'"37fca74771bc76a8e01178ce3a6055a0995f8093"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-69387c31-74d3cfb81844d7c0387d1d34;c4fdfa7c-85bb-4e97-8df8-13c538fca149'), (b'RateLimit', b'"resolvers";r=19988;t=23'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=20000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'5c38ec7c405ec4b44b94cc5a9bb96e735b38267a'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'tokenizer_config.json; filename="tokenizer_config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 12468094e35c8a577a333f469209441a.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'DEN53-P4'), (b'X-Amz-Cf-Id', b'i-JMhLjZH_PwniBX0FH5KHXc-YKEgACfhU-BCU3xHQYJMxIDMAMByw=='), (b'Age', b'1298769')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/tokenizer_config.json "HTTP/1.1 200 OK"
HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/tokenizer_config.json "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
response_closed.started
DEBUG:httpcore.http11:response_closed.complete
response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'application/json; charset=utf-8'), (b'Content-Length', b'64'), (b'Connection', b'keep-alive'), (b'Date', b'Wed, 24 Dec 2025 20:30:58 GMT'), (b'ETag', b'W/"40-09f9IAqP13xarAhQxFS2W8rvRkM"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-694c4d82-34df8ea33746a4c03fb82adc;220c6a49-108d-441b-ac31-f919e22d4342'), (b'RateLimit', b'"api";r=2999;t=254'), (b'RateLimit-Policy', b'"fixed window";"api";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'additional_chat_templates does not exist on "main"'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 12468094e35c8a577a333f469209441a.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'DEN53-P4'), (b'X-Amz-Cf-Id', b'Bm0h7xj0na1tsZOuenA4DkVGViUY1EjoPMvFmXWZ8iv8cZap2MU3qw==')])
receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'application/json; charset=utf-8'), (b'Content-Length', b'64'), (b'Connection', b'keep-alive'), (b'Date', b'Wed, 24 Dec 2025 20:30:58 GMT'), (b'ETag', b'W/"40-09f9IAqP13xarAhQxFS2W8rvRkM"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-694c4d82-34df8ea33746a4c03fb82adc;220c6a49-108d-441b-ac31-f919e22d4342'), (b'RateLimit', b'"api";r=2999;t=254'), (b'RateLimit-Policy', b'"fixed window";"api";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'additional_chat_templates does not exist on "main"'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 12468094e35c8a577a333f469209441a.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'DEN53-P4'), (b'X-Amz-Cf-Id', b'Bm0h7xj0na1tsZOuenA4DkVGViUY1EjoPMvFmXWZ8iv8cZap2MU3qw==')])
INFO:httpx:HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
response_closed.started
DEBUG:httpcore.http11:response_closed.complete
response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'application/json; charset=utf-8'), (b'Content-Length', b'2242'), (b'Connection', b'keep-alive'), (b'Date', b'Wed, 24 Dec 2025 20:30:58 GMT'), (b'ETag', b'W/"8c2-+B357tswuSDPZQJ4PcEV7JZlfTw"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-694c4d82-00abd4787b6613df1d6c333f;ba1139e6-ce82-460a-8ad0-2b24353bdc33'), (b'RateLimit', b'"api";r=2998;t=254'), (b'RateLimit-Policy', b'"fixed window";"api";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 12468094e35c8a577a333f469209441a.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'DEN53-P4'), (b'X-Amz-Cf-Id', b'GeJwiO55pitU2pHS4eObxCMBnTxoMmsLBhsfkfA3-VTGHsuYCv5NsA==')])
receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'application/json; charset=utf-8'), (b'Content-Length', b'2242'), (b'Connection', b'keep-alive'), (b'Date', b'Wed, 24 Dec 2025 20:30:58 GMT'), (b'ETag', b'W/"8c2-+B357tswuSDPZQJ4PcEV7JZlfTw"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-694c4d82-00abd4787b6613df1d6c333f;ba1139e6-ce82-460a-8ad0-2b24353bdc33'), (b'RateLimit', b'"api";r=2998;t=254'), (b'RateLimit-Policy', b'"fixed window";"api";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 12468094e35c8a577a333f469209441a.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'DEN53-P4'), (b'X-Amz-Cf-Id', b'GeJwiO55pitU2pHS4eObxCMBnTxoMmsLBhsfkfA3-VTGHsuYCv5NsA==')])
INFO:httpx:HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
response_closed.started
DEBUG:httpcore.http11:response_closed.complete
response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'272'), (b'Connection', b'keep-alive'), (b'Date', b'Wed, 24 Dec 2025 20:30:59 GMT'), (b'Location', b'/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/1_Pooling%2Fconfig.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2Fmain%2F1_Pooling%2Fconfig.json=&etag=%221da070f0993788c8851a652170ff013aa54dd519%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-694c4d83-1cced44025bc8a4d08aee384;5c91ca5f-2ba2-421c-a784-2ed173847d94'), (b'RateLimit', b'"resolvers";r=19990;t=253'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=20000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'5c38ec7c405ec4b44b94cc5a9bb96e735b38267a'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'HIT'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"1da070f0993788c8851a652170ff013aa54dd519"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 12468094e35c8a577a333f469209441a.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'DEN53-P4'), (b'X-Amz-Cf-Id', b'95F9erPr3wPJoLv5-rLXx70j_e6Jrsjfvh6eb3W9LKZlHJyC13o2Gg==')])

### FAQ

Connect to Redis Cloud

In [4]:
from llama_index.core import StorageContext, VectorStoreIndex
from llama_index.vector_stores.redis import RedisVectorStore
from redisvl.schema import IndexSchema

redis_conn_string = os.getenv("REDIS_URL")
schema = IndexSchema.from_dict(
    {
        "index": {"name": "FAQ", "prefix": "FAQ"},
        # customize fields that are indexed
        "fields": [
            # required fields for llamaindex
            {"type": "tag", "name": "id"},
            {"type": "tag", "name": "doc_id"},
            {"type": "text", "name": "text"},
            # custom for metadata filtering
            {"type": "tag", "name": "category"},
            # {"type": "tag", "name": "subcategory"},
            # custom vector field for bge-small-en-v1.5 embeddings
            {
                "type": "vector",
                "name": "vector",
                "attrs": {
                    "dims": 384,
                    "algorithm": "hnsw",
                    "distance_metric": "cosine",
                },
            },
        ],
    },
)
vector_store = RedisVectorStore(schema=schema, redis_url=redis_conn_string, overwrite=True)
storage_context = StorageContext.from_defaults(vector_store=vector_store)

13:07:14 redisvl.index.index INFO   Index already exists, overwriting.
13:07:14 redisvl.index.index INFO   Index already exists, overwriting.

Load the FAQ

In [5]:
import pandas as pd

df_faq = pd.read_pickle("../data/pandas/faq_knowledge_base.pkl")
df_faq

,category,subcategory,question,answer,keywords,last_updated,helpful_votes,views
faq_id,,,,,,,,
FAQ000001,booking,reservations,How do I make a reservation?,You can make a reservation through our website...,"book, reserve, reservation, booking",2024-03-09,957,3813
FAQ000002,booking,check-in/out,What is the check-in/check-out time?,Check-in time is 3:00 PM and check-out time is...,"check in, check out, arrival, departure",2024-10-15,967,2793
FAQ000003,booking,modifications,Can I modify my booking?,"Yes, you can modify your booking through our w...","change, modify, update, edit",2024-12-05,443,1929
FAQ000004,booking,cancellations,What is the cancellation policy?,Free cancellation is available up to 48 hours ...,"cancel, refund, cancellation",2024-05-20,611,1300
FAQ000005,booking,special requests,Do you offer early check-in/late check-out?,"Subject to availability, early check-in and la...","early check-in, late check-out, extended stay",2024-12-18,239,3954
FAQ000006,amenities,facilities,What amenities are included?,"Our hotel offers complimentary Wi-Fi, fitness ...","amenities, facilities, services",2024-10-24,855,1860
FAQ000007,amenities,dining,Is breakfast included?,"Yes, breakfast is included with most room rate...","breakfast, dining, restaurant",2024-01-10,365,1943
FAQ000008,amenities,wellness,Do you have a fitness center?,"Yes, our fitness center is open 24/7 and featu...","fitness, gym, exercise",2024-10-05,988,1471
FAQ000009,amenities,business,Is there a swimming pool?,"Yes, we have both indoor and outdoor pools ope...","pool, swimming, recreation",2024-10-15,400,2881
FAQ000010,amenities,recreation,Do you offer spa services?,"Our full-service spa offers massages, facials,...","spa, wellness, treatments",2024-01-07,145,766
FAQ000011,services,room service,Is room service available?,Room service is available 24/7 with a full men...,"room service, dining, food",2024-04-05,708,2133
FAQ000012,services,housekeeping,Do you offer laundry service?,"Yes, same-day laundry and dry-cleaning service...","laundry, cleaning, housekeeping",2024-09-16,126,249
FAQ000013,services,concierge,Is there a business center?,Our business center is open 24/7 and offers co...,"business, work, office",2024-05-25,925,1604
FAQ000014,services,transportation,Do you provide airport transfers?,"Yes, we offer airport shuttle service for a fe...","airport, shuttle, transfer",2024-11-27,743,1621
FAQ000015,services,business,Is parking available?,We offer both self-parking and valet parking s...,"parking, valet, car",2024-02-03,721,1975
FAQ000016,policies,pet policy,What is your pet policy?,We welcome pets under 25 pounds for an additio...,"pets, animals, dogs, cats",2024-07-17,639,4327
FAQ000017,policies,smoking policy,Do you have smoking rooms?,All our rooms are non-smoking. Smoking is only...,"smoking, non-smoking, tobacco",2024-01-31,703,2992
FAQ000018,policies,payment policy,What forms of payment do you accept?,"We accept all major credit cards, debit cards,...","payment, credit card, cash",2024-10-30,799,2778
FAQ000019,policies,age requirements,Is there a minimum age to check in?,Guests must be 18 or older to check in. Valid ...,"age, check-in, requirements",2024-01-09,662,4150
FAQ000020,policies,luggage policy,What is your luggage storage policy?,Complimentary luggage storage is available bef...,"luggage, storage, bags",2024-06-20,127,213

Prepare data for storage

In [29]:
from llama_index.core.schema import TextNode

def get_faq_nodes():
    nodes = []
    for id_, row in df_faq.iterrows():
        main_text = "Question:\n" + row["question"] + "\n\nAnswer:\n" + row["answer"]
        metadata = {"category": row["category"],
                    "subcategory": row["subcategory"],
                    "keywords": row["keywords"],
                    "last_updated": row["last_updated"]}
        node = TextNode(text=main_text, id_=id_, metadata=metadata)
        nodes.append(node)
    return nodes

nodes = get_faq_nodes()

Store in vector store

In [7]:
index = VectorStoreIndex(nodes=nodes, storage_context=storage_context)

13:07:14 llama_index.vector_stores.redis.base INFO   Added 20 documents to index FAQ
13:07:14 llama_index.vector_stores.redis.base INFO   Added 20 documents to index FAQ

Setup and test retrieval

In [8]:
retriever = index.as_retriever(similarity_top_k=3)

In [9]:
retriever.retrieve("Is there a place to swim?")

13:07:15 llama_index.vector_stores.redis.base INFO   Querying index FAQ with query *=>[KNN 3 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 3
13:07:15 llama_index.vector_stores.redis.base INFO   Querying index FAQ with query *=>[KNN 3 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 3
13:07:15 llama_index.vector_stores.redis.base INFO   Found 3 results for query with id ['FAQ:FAQ000009', 'FAQ:FAQ000006', 'FAQ:FAQ000010']
13:07:15 llama_index.vector_stores.redis.base INFO   Found 3 results for query with id ['FAQ:FAQ000009', 'FAQ:FAQ000006', 'FAQ:FAQ000010']

[NodeWithScore(node=TextNode(id_='FAQ000009', embedding=None, metadata={'category': 'amenities', 'subcategory': 'business', 'keywords': 'pool, swimming, recreation', 'last_updated': '2024-10-15'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Question:\nIs there a swimming pool?\n\nAnswer:\nYes, we have both indoor and outdoor pools open from 6:00 AM to 10:00 PM.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.741773724556),
 NodeWithScore(node=TextNode(id_='FAQ000006', embedding=None, metadata={'category': 'amenities', 'subcategory': 'facilities', 'keywords': 'amenities, facilities, services', 'last_updated': '2024-10-24'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Question:\nWhat amenities are included?\n\nAnswer:\nOur hotel offers complimentary Wi-Fi, fitness center, pool, spa, restaurant, and 24-hour room service.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.651285409927),
 NodeWithScore(node=TextNode(id_='FAQ000010', embedding=None, metadata={'category': 'amenities', 'subcategory': 'recreation', 'keywords': 'spa, wellness, treatments', 'last_updated': '2024-01-07'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Question:\nDo you offer spa services?\n\nAnswer:\nOur full-service spa offers massages, facials, and body treatments. Advance booking is recommended.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.650461614132)]

Setup and auto-retriever that filters over metadata

In [10]:
from llama_index.core.retrievers import VectorIndexAutoRetriever
from llama_index.core.vector_stores.types import MetadataInfo, VectorStoreInfo

faq_store_info = VectorStoreInfo(
    content_info="FAQs and their answers for the hotel",
    metadata_info=[
        MetadataInfo(
            name="category",
            type="str",
            description=f"Category of the FAQ, one of {df_faq["category"].unique().tolist()}",
        ),
        # MetadataInfo(
        #     name="subcategory",
        #     type="str",
        #     description=f"Subcategory of the FAQ, one of {df_faq["subcategory"].unique().tolist()}"
        # ),
    ],
)
retriever=VectorIndexAutoRetriever(index, vector_store_info=faq_store_info)

The auto-retriever clearly doesn't work for the FAQs.

In [11]:
retriever.retrieve("Is there a place to swim?")

13:07:18 httpx INFO   HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
13:07:18 httpx INFO   HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
13:07:18 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using query str: place to swim
13:07:18 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using query str: place to swim
13:07:18 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using filters: [('category', '==', 'services')]
13:07:18 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using filters: [('category', '==', 'services')]
13:07:18 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using top_k: 2
13:07:18 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using top_k: 2
13:07:18 llama_index.vector_stores.redis.base INFO   Querying index FAQ with query @category:{services}=>[KNN 2 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 2
13:07:18 llama_index.vector_stores.redis.base INFO   Querying index FAQ with query @category:{services}=>[KNN 2 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 2
13:07:18 llama_index.vector_stores.redis.base INFO   Found 2 results for query with id ['FAQ:FAQ000011', 'FAQ:FAQ000013']
13:07:18 llama_index.vector_stores.redis.base INFO   Found 2 results for query with id ['FAQ:FAQ000011', 'FAQ:FAQ000013']

[NodeWithScore(node=TextNode(id_='FAQ000011', embedding=None, metadata={'category': 'services', 'subcategory': 'room service', 'keywords': 'room service, dining, food', 'last_updated': '2024-04-05'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Question:\nIs room service available?\n\nAnswer:\nRoom service is available 24/7 with a full menu during restaurant hours and a limited menu overnight.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.581247210503),
 NodeWithScore(node=TextNode(id_='FAQ000013', embedding=None, metadata={'category': 'services', 'subcategory': 'concierge', 'keywords': 'business, work, office', 'last_updated': '2024-05-25'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Question:\nIs there a business center?\n\nAnswer:\nOur business center is open 24/7 and offers computers, printing, and meeting rooms.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.578524112701)]

In [12]:
retriever.retrieve("What's the policy on smoking?")

13:07:20 httpx INFO   HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
13:07:20 httpx INFO   HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
13:07:20 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using query str: policy on smoking
13:07:20 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using query str: policy on smoking
13:07:20 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using filters: [('category', '==', 'policies')]
13:07:20 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using filters: [('category', '==', 'policies')]
13:07:20 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using top_k: 2
13:07:20 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using top_k: 2
13:07:20 llama_index.vector_stores.redis.base INFO   Querying index FAQ with query @category:{policies}=>[KNN 2 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 2
13:07:20 llama_index.vector_stores.redis.base INFO   Querying index FAQ with query @category:{policies}=>[KNN 2 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 2
13:07:20 llama_index.vector_stores.redis.base INFO   Found 2 results for query with id ['FAQ:FAQ000017', 'FAQ:FAQ000016']
13:07:20 llama_index.vector_stores.redis.base INFO   Found 2 results for query with id ['FAQ:FAQ000017', 'FAQ:FAQ000016']

[NodeWithScore(node=TextNode(id_='FAQ000017', embedding=None, metadata={'category': 'policies', 'subcategory': 'smoking policy', 'keywords': 'smoking, non-smoking, tobacco', 'last_updated': '2024-01-31'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Question:\nDo you have smoking rooms?\n\nAnswer:\nAll our rooms are non-smoking. Smoking is only permitted in designated outdoor areas.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.786777734756),
 NodeWithScore(node=TextNode(id_='FAQ000016', embedding=None, metadata={'category': 'policies', 'subcategory': 'pet policy', 'keywords': 'pets, animals, dogs, cats', 'last_updated': '2024-07-17'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Question:\nWhat is your pet policy?\n\nAnswer:\nWe welcome pets under 25 pounds for an additional fee. Please notify us in advance.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.6674103736879999)]

### Amenities

Connect to Redis Cloud

In [25]:
from llama_index.core import StorageContext, VectorStoreIndex
from llama_index.vector_stores.redis import RedisVectorStore
from redisvl.schema import IndexSchema

redis_conn_string = os.getenv("REDIS_URL")
schema = IndexSchema.from_dict(
    {
        "index": {"name": "Amenities", "prefix": "Amenities"},
        # customize fields that are indexed
        "fields": [
            # required fields for llamaindex
            {"type": "tag", "name": "id"},
            {"type": "tag", "name": "doc_id"},
            {"type": "text", "name": "text"},
            # custom fields for filtering
            {"type": "tag", "name": "category"},
            {"type": "numeric", "name": "price"},
            {"type": "numeric", "name": "duration"},
            {"type": "numeric", "name": "min_notice_hours"},
            # custom vector field for bge-small-en-v1.5 embeddings
            {
                "type": "vector",
                "name": "vector",
                "attrs": {
                    "dims": 384,
                    "algorithm": "hnsw",
                    "distance_metric": "cosine",
                },
            },
        ],
    },
)
vector_store = RedisVectorStore(schema=schema, redis_url=redis_conn_string, overwrite=True)
storage_context = StorageContext.from_defaults(vector_store=vector_store)

13:14:20 redisvl.index.index INFO   Index already exists, overwriting.
13:14:20 redisvl.index.index INFO   Index already exists, overwriting.

Add amenity information

In [14]:
df_amenities = pd.read_pickle("../data/pandas/amenities.pkl")
df_amenities.head()

,category,name,price,duration,description,availability,location,booking_required,min_notice_hours
amenity_id,,,,,,,,,
AM000001,Spa Services,Swedish Massage,120,60,Experience pure relaxation with our Swedish Ma...,24/7,Spa & Wellness Center,True,2
AM000002,Spa Services,Deep Tissue Massage,140,60,"Indulge in our signature Deep Tissue Massage, ...",6:00-22:00,Spa & Wellness Center,False,4
AM000003,Spa Services,Couples Massage Experience,280,90,Indulge in our signature Couples Massage Exper...,By appointment only,Spa & Wellness Center,False,0
AM000004,Spa Services,Hot Stone Therapy,160,90,Experience pure relaxation with our Hot Stone ...,6:00-22:00,Pool Area,False,1
AM000005,Spa Services,Luxury Facial Treatment,180,90,Indulge in our signature Luxury Facial Treatme...,24/7,Main Building,False,24

Prepare data for storage

In [28]:
def get_amenities_nodes():
    nodes = []
    for id_, row in df_amenities.iterrows():
        main_text = "Name:" + row["name"] + "\n\nDescription:\n" + row["description"]
        metadata = {"category": row["category"],
                    "price": row["price"],
                    "duration": row["duration"],
                    "availability": row["availability"],
                    "location": row["location"],
                    "booking_required": str(row["booking_required"]),
                    "min_notice_hours": row["min_notice_hours"]}
        node = TextNode(text=main_text, id_=id_, metadata=metadata)
        nodes.append(node)
    return nodes

nodes = get_amenities_nodes()

Store in vector store, setup retriever

In [27]:
index = VectorStoreIndex(nodes=nodes, storage_context=storage_context)
retriever = index.as_retriever(similarity_top_k=3)

13:14:41 llama_index.vector_stores.redis.base INFO   Added 34 documents to index Amenities
13:14:41 llama_index.vector_stores.redis.base INFO   Added 34 documents to index Amenities

In [17]:
retriever.retrieve("Can I get a massage?")

13:07:21 llama_index.vector_stores.redis.base INFO   Querying index Amenities with query *=>[KNN 3 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 3
13:07:21 llama_index.vector_stores.redis.base INFO   Querying index Amenities with query *=>[KNN 3 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 3
13:07:21 llama_index.vector_stores.redis.base INFO   Found 3 results for query with id ['Amenities:AM000003', 'Amenities:AM000002', 'Amenities:AM000001']
13:07:21 llama_index.vector_stores.redis.base INFO   Found 3 results for query with id ['Amenities:AM000003', 'Amenities:AM000002', 'Amenities:AM000001']

[NodeWithScore(node=TextNode(id_='AM000003', embedding=None, metadata={'category': 'Spa Services', 'price': 280, 'duration': 90, 'availability': 'By appointment only', 'location': 'Spa & Wellness Center', 'booking_required': 'False', 'min_notice_hours': 0}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Name:Couples Massage Experience\n\nDescription:\nIndulge in our signature Couples Massage Experience, where 90 minutes of expert care will melt away stress and tension. This treatment features therapeutic-grade materials and customized therapeutic approaches to provide rejuvenated and restored.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.6567953825),
 NodeWithScore(node=TextNode(id_='AM000002', embedding=None, metadata={'category': 'Spa Services', 'price': 140, 'duration': 60, 'availability': '6:00-22:00', 'location': 'Spa & Wellness Center', 'booking_required': 'False', 'min_notice_hours': 4}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Name:Deep Tissue Massage\n\nDescription:\nIndulge in our signature Deep Tissue Massage, where 60 minutes of expert care will melt away stress and tension. This treatment features natural skincare products and customized therapeutic approaches to provide rejuvenated and restored.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.653777182102),
 NodeWithScore(node=TextNode(id_='AM000001', embedding=None, metadata={'category': 'Spa Services', 'price': 120, 'duration': 60, 'availability': '24/7', 'location': 'Spa & Wellness Center', 'booking_required': 'True', 'min_notice_hours': 2}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Name:Swedish Massage\n\nDescription:\nExperience pure relaxation with our Swedish Massage, a 60-minute treatment designed to melt away stress and tension. Our certified therapists use premium natural skincare products to precise pressure point therapy, leaving you feeling renewed and revitalized.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.648089170456)]

Setup and auto-retriever that filters over metadata

In [18]:
from llama_index.core.retrievers import VectorIndexAutoRetriever
from llama_index.core.vector_stores.types import MetadataInfo, VectorStoreInfo

amenities_store_info = VectorStoreInfo(
    content_info="Information about hotel amenities (services)",
    metadata_info=[
        MetadataInfo(
            name="category",
            type="string",
            description=f"Category of the amenity, one of {df_amenities["category"].unique().tolist()}",
        ),
        MetadataInfo(
            name="price",
            type="integer",
            description="The cost of the amenity in dollars.",
        ),
        MetadataInfo(
            name="duration",
            type="integer",
            description="The duration of the amenity in minutes. Do not use quotes. Output as a raw integer.",
        ),
        MetadataInfo(
            name="min_notice_hours",
            type="integer",
            description="How far in advance the request for the amenity needs to be made in hours.",
        ),
    ],
)
retriever=VectorIndexAutoRetriever(index, vector_store_info=amenities_store_info, similarity_top_k=3)

In [19]:
retriever.retrieve("I would like an hour long massage")

13:07:22 httpx INFO   HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
13:07:22 httpx INFO   HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
13:07:22 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using query str: hour long massage
13:07:22 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using query str: hour long massage
13:07:22 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using filters: [('duration', '==', '60'), ('category', '==', 'Spa Services')]
13:07:22 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using filters: [('duration', '==', '60'), ('category', '==', 'Spa Services')]
13:07:22 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using top_k: 3
13:07:22 llama_index.core.indices.vector_store.retrievers.auto_retriever.auto_retriever INFO   Using top_k: 3

TypeError: Right side argument passed to operator == with left side argument Num must be of type (<class 'int'>, <class 'float'>, <class 'NoneType'>)

### Services

I would like to combine this with amenities as the dataset columns are almost identical, but this set doesn't have availability information. In practice, I would just ask for this information, but I can't do that here, so I'm keeping them separate.

Connect to Redis Cloud

In [20]:
from llama_index.core import StorageContext, VectorStoreIndex
from llama_index.vector_stores.redis import RedisVectorStore
from redisvl.schema import IndexSchema

redis_conn_string = os.getenv("REDIS_URL")
schema = IndexSchema.from_dict(
    {
        "index": {"name": "Services", "prefix": "Services"},
        # customize fields that are indexed
        "fields": [
            # required fields for llamaindex
            {"type": "tag", "name": "id"},
            {"type": "tag", "name": "doc_id"},
            {"type": "text", "name": "text"},
            # custom vector field for bge-small-en-v1.5 embeddings
            {
                "type": "vector",
                "name": "vector",
                "attrs": {
                    "dims": 384,
                    "algorithm": "hnsw",
                    "distance_metric": "cosine",
                },
            },
        ],
    },
)
vector_store = RedisVectorStore(schema=schema, redis_url=redis_conn_string, overwrite=True)
storage_context = StorageContext.from_defaults(vector_store=vector_store)

13:07:28 redisvl.index.index INFO   Index already exists, overwriting.
13:07:28 redisvl.index.index INFO   Index already exists, overwriting.

Add services information

In [21]:
df_services = pd.read_pickle("../data/pandas/services.pkl")
df_services.head()

,service_type,name,description,duration_minutes,price,department,booking_required,min_notice_hours
service_id,,,,,,,,
SV000001,Spa Treatment,Spa Treatment - 120 min,Swedish massage for 120 minutes using Modern t...,120,264.98,Spa & Wellness,True,4
SV000002,Spa Treatment,Spa Treatment - 60 min,Luxurious 60-minute Deep Tissue treatment feat...,60,232.03,Spa & Wellness,True,4
SV000003,Spa Treatment,Spa Treatment - 120 min,Premium Deep Tissue experience for 120 minutes...,120,251.99,Spa & Wellness,True,24
SV000004,Spa Treatment,Spa Treatment - 90 min,Luxurious 90-minute Hot Stone treatment featur...,90,157.55,Spa & Wellness,True,1
SV000005,Personal Training,Personal Training - 60 min,Custom 60-minute HIIT workout emphasizing Core...,60,133.13,Fitness Center,True,4

In [30]:
def get_services_nodes():
    nodes = []
    for id_, row in df_services.iterrows():
        main_text = "Name:" + row["name"] + "\n\nDescription:\n" + row["description"]
        metadata = {"service_type": row["service_type"],
                    "duration_minutes": row["duration_minutes"],
                    "price": row["price"],
                    "department": row["department"],
                    "booking_required": str(row["booking_required"]),
                    "min_notice_hours": row["min_notice_hours"]}
        node = TextNode(text=main_text, id_=id_, metadata=metadata)
        nodes.append(node)
    return nodes

nodes = get_services_nodes()

In [23]:
index = VectorStoreIndex(nodes=nodes, storage_context=storage_context)
retriever = index.as_retriever(similarity_top_k=3)

13:07:35 llama_index.vector_stores.redis.base INFO   Added 25 documents to index Services
13:07:35 llama_index.vector_stores.redis.base INFO   Added 25 documents to index Services

In [24]:
retriever.retrieve("I want to do some pilates.")

13:07:36 llama_index.vector_stores.redis.base INFO   Querying index Services with query *=>[KNN 3 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 3
13:07:36 llama_index.vector_stores.redis.base INFO   Querying index Services with query *=>[KNN 3 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 3
13:07:36 llama_index.vector_stores.redis.base INFO   Found 3 results for query with id ['Services:SV000024', 'Services:SV000008', 'Services:SV000007']
13:07:36 llama_index.vector_stores.redis.base INFO   Found 3 results for query with id ['Services:SV000024', 'Services:SV000008', 'Services:SV000007']

[NodeWithScore(node=TextNode(id_='SV000024', embedding=None, metadata={'service_type': 'Group Fitness Class', 'duration_minutes': 45, 'price': 30.93, 'department': 'Fitness Center', 'booking_required': 'True', 'min_notice_hours': 1}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Name:Group Fitness Class - 45 min\n\nDescription:\nEngaging 45-minute Pilates class emphasizing Strength. Group Motivation.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.663864791393),
 NodeWithScore(node=TextNode(id_='SV000008', embedding=None, metadata={'service_type': 'Personal Training', 'duration_minutes': 60, 'price': 143.7, 'department': 'Fitness Center', 'booking_required': 'True', 'min_notice_hours': 2}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Name:Personal Training - 60 min\n\nDescription:\nCustom 60-minute Strength Training workout emphasizing Full Body. Better Flexibility.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.573877573013),
 NodeWithScore(node=TextNode(id_='SV000007', embedding=None, metadata={'service_type': 'Personal Training', 'duration_minutes': 60, 'price': 82.2, 'department': 'Fitness Center', 'booking_required': 'True', 'min_notice_hours': 24}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Name:Personal Training - 60 min\n\nDescription:\nPersonalized Functional Fitness training for 60 minutes targeting Lower Body. Enhanced Endurance.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.570849835873)]

Since I can't get the auto-retriever to work with Redis, I'm just going to stick the FAQ, services, and amenities in the same index. If I have time, I will look at using a different vector database that works with the auto-retriever.

In [32]:
redis_conn_string = os.getenv("REDIS_URL")
schema = IndexSchema.from_dict(
    {
        "index": {"name": "blue_horizon", "prefix": "blue_horizon"},
        # customize fields that are indexed
        "fields": [
            # required fields for llamaindex
            {"type": "tag", "name": "id"},
            {"type": "tag", "name": "doc_id"},
            {"type": "text", "name": "text"},
            # custom vector field for bge-small-en-v1.5 embeddings
            {
                "type": "vector",
                "name": "vector",
                "attrs": {
                    "dims": 384,
                    "algorithm": "hnsw",
                    "distance_metric": "cosine",
                },
            },
        ],
    },
)
vector_store = RedisVectorStore(schema=schema, redis_url=redis_conn_string, overwrite=True)
storage_context = StorageContext.from_defaults(vector_store=vector_store)

13:21:39 redisvl.index.index INFO   Index already exists, overwriting.
13:21:39 redisvl.index.index INFO   Index already exists, overwriting.

In [31]:
faq_nodes = get_faq_nodes()
amenities_nodes = get_amenities_nodes()
services_nodes = get_services_nodes()

In [33]:
index = VectorStoreIndex(nodes=faq_nodes, storage_context=storage_context)
index.insert_nodes(amenities_nodes)
index.insert_nodes(services_nodes)

13:22:27 llama_index.vector_stores.redis.base INFO   Added 20 documents to index blue_horizon
13:22:27 llama_index.vector_stores.redis.base INFO   Added 20 documents to index blue_horizon
13:22:27 llama_index.vector_stores.redis.base INFO   Added 34 documents to index blue_horizon
13:22:27 llama_index.vector_stores.redis.base INFO   Added 34 documents to index blue_horizon
13:22:28 llama_index.vector_stores.redis.base INFO   Added 25 documents to index blue_horizon
13:22:28 llama_index.vector_stores.redis.base INFO   Added 25 documents to index blue_horizon

In [34]:
retriever = index.as_retriever(similarity_top_k=3)
retriever.retrieve("Can I go for a swim?")

13:23:27 llama_index.vector_stores.redis.base INFO   Querying index blue_horizon with query *=>[KNN 3 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 3
13:23:27 llama_index.vector_stores.redis.base INFO   Querying index blue_horizon with query *=>[KNN 3 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 3
13:23:27 llama_index.vector_stores.redis.base INFO   Found 3 results for query with id ['blue_horizon:FAQ000009', 'blue_horizon:FAQ000010', 'blue_horizon:FAQ000005']
13:23:27 llama_index.vector_stores.redis.base INFO   Found 3 results for query with id ['blue_horizon:FAQ000009', 'blue_horizon:FAQ000010', 'blue_horizon:FAQ000005']

[NodeWithScore(node=TextNode(id_='FAQ000009', embedding=None, metadata={'category': 'amenities', 'subcategory': 'business', 'keywords': 'pool, swimming, recreation', 'last_updated': '2024-10-15'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Question:\nIs there a swimming pool?\n\nAnswer:\nYes, we have both indoor and outdoor pools open from 6:00 AM to 10:00 PM.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.686123907566),
 NodeWithScore(node=TextNode(id_='FAQ000010', embedding=None, metadata={'category': 'amenities', 'subcategory': 'recreation', 'keywords': 'spa, wellness, treatments', 'last_updated': '2024-01-07'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Question:\nDo you offer spa services?\n\nAnswer:\nOur full-service spa offers massages, facials, and body treatments. Advance booking is recommended.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.644719541073),
 NodeWithScore(node=TextNode(id_='FAQ000005', embedding=None, metadata={'category': 'booking', 'subcategory': 'special requests', 'keywords': 'early check-in, late check-out, extended stay', 'last_updated': '2024-12-18'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Question:\nDo you offer early check-in/late check-out?\n\nAnswer:\nSubject to availability, early check-in and late check-out can be arranged for an additional fee.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.629732251167)]

In [35]:
retriever.retrieve("Can I get a massage?")

13:23:58 llama_index.vector_stores.redis.base INFO   Querying index blue_horizon with query *=>[KNN 3 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 3
13:23:58 llama_index.vector_stores.redis.base INFO   Querying index blue_horizon with query *=>[KNN 3 @vector $vector AS vector_distance] RETURN 5 id doc_id text _node_content vector_distance SORTBY vector_distance ASC DIALECT 2 LIMIT 0 3
13:23:58 llama_index.vector_stores.redis.base INFO   Found 3 results for query with id ['blue_horizon:FAQ000010', 'blue_horizon:AM000003', 'blue_horizon:AM000002']
13:23:58 llama_index.vector_stores.redis.base INFO   Found 3 results for query with id ['blue_horizon:FAQ000010', 'blue_horizon:AM000003', 'blue_horizon:AM000002']

[NodeWithScore(node=TextNode(id_='FAQ000010', embedding=None, metadata={'category': 'amenities', 'subcategory': 'recreation', 'keywords': 'spa, wellness, treatments', 'last_updated': '2024-01-07'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Question:\nDo you offer spa services?\n\nAnswer:\nOur full-service spa offers massages, facials, and body treatments. Advance booking is recommended.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.7244102358819999),
 NodeWithScore(node=TextNode(id_='AM000003', embedding=None, metadata={'category': 'Spa Services', 'price': 280, 'duration': 90, 'availability': 'By appointment only', 'location': 'Spa & Wellness Center', 'booking_required': 'False', 'min_notice_hours': 0}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Name:Couples Massage Experience\n\nDescription:\nIndulge in our signature Couples Massage Experience, where 90 minutes of expert care will melt away stress and tension. This treatment features therapeutic-grade materials and customized therapeutic approaches to provide rejuvenated and restored.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.6567953825),
 NodeWithScore(node=TextNode(id_='AM000002', embedding=None, metadata={'category': 'Spa Services', 'price': 140, 'duration': 60, 'availability': '6:00-22:00', 'location': 'Spa & Wellness Center', 'booking_required': 'False', 'min_notice_hours': 4}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Name:Deep Tissue Massage\n\nDescription:\nIndulge in our signature Deep Tissue Massage, where 60 minutes of expert care will melt away stress and tension. This treatment features natural skincare products and customized therapeutic approaches to provide rejuvenated and restored.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=0.653777182102)]